// Code generated by ent, DO NOT EDIT.

package milestone

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the milestone type in the database.
	Label = "milestone"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMilestoneType holds the string denoting the milestone_type field in the database.
	FieldMilestoneType = "milestone_type"
	// FieldEventDate holds the string denoting the event_date field in the database.
	FieldEventDate = "event_date"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldOfficiatedBy holds the string denoting the officiated_by field in the database.
	FieldOfficiatedBy = "officiated_by"
	// FieldContactID holds the string denoting the contact_id field in the database.
	FieldContactID = "contact_id"
	// FieldChurchID holds the string denoting the church_id field in the database.
	FieldChurchID = "church_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMember holds the string denoting the member edge name in mutations.
	EdgeMember = "member"
	// EdgeChurch holds the string denoting the church edge name in mutations.
	EdgeChurch = "church"
	// Table holds the table name of the milestone in the database.
	Table = "milestones"
	// MemberTable is the table that holds the member relation/edge.
	MemberTable = "milestones"
	// MemberInverseTable is the table name for the Contact entity.
	// It exists in this package in order to avoid circular dependency with the "contact" package.
	MemberInverseTable = "contacts"
	// MemberColumn is the table column denoting the member relation/edge.
	MemberColumn = "contact_id"
	// ChurchTable is the table that holds the church relation/edge.
	ChurchTable = "milestones"
	// ChurchInverseTable is the table name for the Church entity.
	// It exists in this package in order to avoid circular dependency with the "church" package.
	ChurchInverseTable = "churches"
	// ChurchColumn is the table column denoting the church relation/edge.
	ChurchColumn = "church_id"
)

// Columns holds all SQL columns for milestone fields.
var Columns = []string{
	FieldID,
	FieldMilestoneType,
	FieldEventDate,
	FieldDescription,
	FieldOfficiatedBy,
	FieldContactID,
	FieldChurchID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// MilestoneType defines the type for the "milestone_type" enum field.
type MilestoneType string

// MilestoneType values.
const (
	MilestoneTypeBabyDedication MilestoneType = "baby_dedication"
	MilestoneTypeConfirmation   MilestoneType = "confirmation"
	MilestoneTypeMembership     MilestoneType = "membership"
	MilestoneTypeMarriage       MilestoneType = "marriage"
	MilestoneTypeOrdination     MilestoneType = "ordination"
	MilestoneTypeOther          MilestoneType = "other"
)

func (mt MilestoneType) String() string {
	return string(mt)
}

// MilestoneTypeValidator is a validator for the "milestone_type" field enum values. It is called by the builders before save.
func MilestoneTypeValidator(mt MilestoneType) error {
	switch mt {
	case MilestoneTypeBabyDedication, MilestoneTypeConfirmation, MilestoneTypeMembership, MilestoneTypeMarriage, MilestoneTypeOrdination, MilestoneTypeOther:
		return nil
	default:
		return fmt.Errorf("milestone: invalid enum value for milestone_type field: %q", mt)
	}
}

// OrderOption defines the ordering options for the Milestone queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMilestoneType orders the results by the milestone_type field.
func ByMilestoneType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMilestoneType, opts...).ToFunc()
}

// ByEventDate orders the results by the event_date field.
func ByEventDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventDate, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByOfficiatedBy orders the results by the officiated_by field.
func ByOfficiatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfficiatedBy, opts...).ToFunc()
}

// ByContactID orders the results by the contact_id field.
func ByContactID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactID, opts...).ToFunc()
}

// ByChurchID orders the results by the church_id field.
func ByChurchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChurchID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMemberField orders the results by member field.
func ByMemberField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberStep(), sql.OrderByField(field, opts...))
	}
}

// ByChurchField orders the results by church field.
func ByChurchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChurchStep(), sql.OrderByField(field, opts...))
	}
}
func newMemberStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
	)
}
func newChurchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChurchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChurchTable, ChurchColumn),
	)
}
