// Code generated by ent, DO NOT EDIT.

package milestone

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ntiGideon/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldID, id))
}

// EventDate applies equality check predicate on the "event_date" field. It's identical to EventDateEQ.
func EventDate(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldEventDate, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldDescription, v))
}

// OfficiatedBy applies equality check predicate on the "officiated_by" field. It's identical to OfficiatedByEQ.
func OfficiatedBy(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldOfficiatedBy, v))
}

// ContactID applies equality check predicate on the "contact_id" field. It's identical to ContactIDEQ.
func ContactID(v int) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldContactID, v))
}

// ChurchID applies equality check predicate on the "church_id" field. It's identical to ChurchIDEQ.
func ChurchID(v int) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldChurchID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldCreatedAt, v))
}

// MilestoneTypeEQ applies the EQ predicate on the "milestone_type" field.
func MilestoneTypeEQ(v MilestoneType) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldMilestoneType, v))
}

// MilestoneTypeNEQ applies the NEQ predicate on the "milestone_type" field.
func MilestoneTypeNEQ(v MilestoneType) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldMilestoneType, v))
}

// MilestoneTypeIn applies the In predicate on the "milestone_type" field.
func MilestoneTypeIn(vs ...MilestoneType) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldMilestoneType, vs...))
}

// MilestoneTypeNotIn applies the NotIn predicate on the "milestone_type" field.
func MilestoneTypeNotIn(vs ...MilestoneType) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldMilestoneType, vs...))
}

// EventDateEQ applies the EQ predicate on the "event_date" field.
func EventDateEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldEventDate, v))
}

// EventDateNEQ applies the NEQ predicate on the "event_date" field.
func EventDateNEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldEventDate, v))
}

// EventDateIn applies the In predicate on the "event_date" field.
func EventDateIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldEventDate, vs...))
}

// EventDateNotIn applies the NotIn predicate on the "event_date" field.
func EventDateNotIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldEventDate, vs...))
}

// EventDateGT applies the GT predicate on the "event_date" field.
func EventDateGT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldEventDate, v))
}

// EventDateGTE applies the GTE predicate on the "event_date" field.
func EventDateGTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldEventDate, v))
}

// EventDateLT applies the LT predicate on the "event_date" field.
func EventDateLT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldEventDate, v))
}

// EventDateLTE applies the LTE predicate on the "event_date" field.
func EventDateLTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldEventDate, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContainsFold(FieldDescription, v))
}

// OfficiatedByEQ applies the EQ predicate on the "officiated_by" field.
func OfficiatedByEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldOfficiatedBy, v))
}

// OfficiatedByNEQ applies the NEQ predicate on the "officiated_by" field.
func OfficiatedByNEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldOfficiatedBy, v))
}

// OfficiatedByIn applies the In predicate on the "officiated_by" field.
func OfficiatedByIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldOfficiatedBy, vs...))
}

// OfficiatedByNotIn applies the NotIn predicate on the "officiated_by" field.
func OfficiatedByNotIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldOfficiatedBy, vs...))
}

// OfficiatedByGT applies the GT predicate on the "officiated_by" field.
func OfficiatedByGT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldOfficiatedBy, v))
}

// OfficiatedByGTE applies the GTE predicate on the "officiated_by" field.
func OfficiatedByGTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldOfficiatedBy, v))
}

// OfficiatedByLT applies the LT predicate on the "officiated_by" field.
func OfficiatedByLT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldOfficiatedBy, v))
}

// OfficiatedByLTE applies the LTE predicate on the "officiated_by" field.
func OfficiatedByLTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldOfficiatedBy, v))
}

// OfficiatedByContains applies the Contains predicate on the "officiated_by" field.
func OfficiatedByContains(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContains(FieldOfficiatedBy, v))
}

// OfficiatedByHasPrefix applies the HasPrefix predicate on the "officiated_by" field.
func OfficiatedByHasPrefix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasPrefix(FieldOfficiatedBy, v))
}

// OfficiatedByHasSuffix applies the HasSuffix predicate on the "officiated_by" field.
func OfficiatedByHasSuffix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasSuffix(FieldOfficiatedBy, v))
}

// OfficiatedByIsNil applies the IsNil predicate on the "officiated_by" field.
func OfficiatedByIsNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldIsNull(FieldOfficiatedBy))
}

// OfficiatedByNotNil applies the NotNil predicate on the "officiated_by" field.
func OfficiatedByNotNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldNotNull(FieldOfficiatedBy))
}

// OfficiatedByEqualFold applies the EqualFold predicate on the "officiated_by" field.
func OfficiatedByEqualFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEqualFold(FieldOfficiatedBy, v))
}

// OfficiatedByContainsFold applies the ContainsFold predicate on the "officiated_by" field.
func OfficiatedByContainsFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContainsFold(FieldOfficiatedBy, v))
}

// ContactIDEQ applies the EQ predicate on the "contact_id" field.
func ContactIDEQ(v int) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldContactID, v))
}

// ContactIDNEQ applies the NEQ predicate on the "contact_id" field.
func ContactIDNEQ(v int) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldContactID, v))
}

// ContactIDIn applies the In predicate on the "contact_id" field.
func ContactIDIn(vs ...int) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldContactID, vs...))
}

// ContactIDNotIn applies the NotIn predicate on the "contact_id" field.
func ContactIDNotIn(vs ...int) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldContactID, vs...))
}

// ChurchIDEQ applies the EQ predicate on the "church_id" field.
func ChurchIDEQ(v int) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldChurchID, v))
}

// ChurchIDNEQ applies the NEQ predicate on the "church_id" field.
func ChurchIDNEQ(v int) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldChurchID, v))
}

// ChurchIDIn applies the In predicate on the "church_id" field.
func ChurchIDIn(vs ...int) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldChurchID, vs...))
}

// ChurchIDNotIn applies the NotIn predicate on the "church_id" field.
func ChurchIDNotIn(vs ...int) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldChurchID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.Milestone {
	return predicate.Milestone(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.Contact) predicate.Milestone {
	return predicate.Milestone(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChurch applies the HasEdge predicate on the "church" edge.
func HasChurch() predicate.Milestone {
	return predicate.Milestone(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChurchTable, ChurchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChurchWith applies the HasEdge predicate on the "church" edge with a given conditions (other predicates).
func HasChurchWith(preds ...predicate.Church) predicate.Milestone {
	return predicate.Milestone(func(s *sql.Selector) {
		step := newChurchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Milestone) predicate.Milestone {
	return predicate.Milestone(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Milestone) predicate.Milestone {
	return predicate.Milestone(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Milestone) predicate.Milestone {
	return predicate.Milestone(sql.NotPredicates(p))
}
