// Code generated by ent, DO NOT EDIT.

package department

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldDepartmentType holds the string denoting the department_type field in the database.
	FieldDepartmentType = "department_type"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeChurch holds the string denoting the church edge name in mutations.
	EdgeChurch = "church"
	// Table holds the table name of the department in the database.
	Table = "departments"
	// ChurchTable is the table that holds the church relation/edge.
	ChurchTable = "departments"
	// ChurchInverseTable is the table name for the Church entity.
	// It exists in this package in order to avoid circular dependency with the "church" package.
	ChurchInverseTable = "churches"
	// ChurchColumn is the table column denoting the church relation/edge.
	ChurchColumn = "church_departments"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldDepartmentType,
	FieldIsActive,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "departments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"church_departments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// DepartmentType defines the type for the "department_type" enum field.
type DepartmentType string

// DepartmentType values.
const (
	DepartmentTypeWorship        DepartmentType = "worship"
	DepartmentTypeYouth          DepartmentType = "youth"
	DepartmentTypeChildren       DepartmentType = "children"
	DepartmentTypeOutreach       DepartmentType = "outreach"
	DepartmentTypeAdministration DepartmentType = "administration"
	DepartmentTypeFinance        DepartmentType = "finance"
	DepartmentTypeMedia          DepartmentType = "media"
)

func (dt DepartmentType) String() string {
	return string(dt)
}

// DepartmentTypeValidator is a validator for the "department_type" field enum values. It is called by the builders before save.
func DepartmentTypeValidator(dt DepartmentType) error {
	switch dt {
	case DepartmentTypeWorship, DepartmentTypeYouth, DepartmentTypeChildren, DepartmentTypeOutreach, DepartmentTypeAdministration, DepartmentTypeFinance, DepartmentTypeMedia:
		return nil
	default:
		return fmt.Errorf("department: invalid enum value for department_type field: %q", dt)
	}
}

// OrderOption defines the ordering options for the Department queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByDepartmentType orders the results by the department_type field.
func ByDepartmentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartmentType, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByChurchField orders the results by church field.
func ByChurchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChurchStep(), sql.OrderByField(field, opts...))
	}
}
func newChurchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChurchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChurchTable, ChurchColumn),
	)
}
