// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnnouncementsColumns holds the columns for the "announcements" table.
	AnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"general", "prayer", "event", "urgent", "financial"}, Default: "general"},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "church_announcements", Type: field.TypeInt},
		{Name: "user_announcements", Type: field.TypeInt, Nullable: true},
	}
	// AnnouncementsTable holds the schema information for the "announcements" table.
	AnnouncementsTable = &schema.Table{
		Name:       "announcements",
		Columns:    AnnouncementsColumns,
		PrimaryKey: []*schema.Column{AnnouncementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "announcements_churches_announcements",
				Columns:    []*schema.Column{AnnouncementsColumns[8]},
				RefColumns: []*schema.Column{ChurchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "announcements_users_announcements",
				Columns:    []*schema.Column{AnnouncementsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ChurchesColumns holds the columns for the "churches" table.
	ChurchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "city", Type: field.TypeString, Default: "Kumasi"},
		{Name: "state", Type: field.TypeString, Nullable: true},
		{Name: "zip_code", Type: field.TypeString, Nullable: true},
		{Name: "country", Type: field.TypeString, Default: "GHANA"},
		{Name: "website", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "registration_token", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "established_date", Type: field.TypeTime, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"headquarters", "branch", "mission"}, Default: "branch"},
		{Name: "latitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "longitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "logo_url", Type: field.TypeString, Nullable: true},
		{Name: "banner_url", Type: field.TypeString, Nullable: true},
		{Name: "congregation_size", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
	}
	// ChurchesTable holds the schema information for the "churches" table.
	ChurchesTable = &schema.Table{
		Name:       "churches",
		Columns:    ChurchesColumns,
		PrimaryKey: []*schema.Column{ChurchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "churches_churches_children",
				Columns:    []*schema.Column{ChurchesColumns[21]},
				RefColumns: []*schema.Column{ChurchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "church_parent_id",
				Unique:  false,
				Columns: []*schema.Column{ChurchesColumns[21]},
			},
			{
				Name:    "church_type",
				Unique:  false,
				Columns: []*schema.Column{ChurchesColumns[12]},
			},
			{
				Name:    "church_is_active",
				Unique:  false,
				Columns: []*schema.Column{ChurchesColumns[18]},
			},
		},
	}
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "middle_name", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "secondary_phone", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "gender", Type: field.TypeEnum, Nullable: true, Enums: []string{"male", "female", "other"}},
		{Name: "date_of_birth", Type: field.TypeTime, Nullable: true},
		{Name: "marital_status", Type: field.TypeEnum, Nullable: true, Enums: []string{"single", "married", "divorced", "widowed"}},
		{Name: "occupation", Type: field.TypeString, Nullable: true},
		{Name: "address_line1", Type: field.TypeString, Nullable: true},
		{Name: "address_line2", Type: field.TypeString, Nullable: true},
		{Name: "city", Type: field.TypeString, Nullable: true},
		{Name: "state", Type: field.TypeString, Nullable: true},
		{Name: "country", Type: field.TypeString, Nullable: true},
		{Name: "postal_code", Type: field.TypeString, Nullable: true},
		{Name: "emergency_contact_name", Type: field.TypeString, Nullable: true},
		{Name: "emergency_contact_phone", Type: field.TypeString, Nullable: true},
		{Name: "emergency_contact_relationship", Type: field.TypeString, Nullable: true},
		{Name: "profile_picture_url", Type: field.TypeString, Nullable: true},
		{Name: "id_number", Type: field.TypeString, Nullable: true},
		{Name: "hometown", Type: field.TypeString, Nullable: true},
		{Name: "region", Type: field.TypeString, Nullable: true},
		{Name: "sunday_school_class", Type: field.TypeString, Nullable: true},
		{Name: "day_born", Type: field.TypeEnum, Nullable: true, Enums: []string{"monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"}},
		{Name: "membership_year", Type: field.TypeInt, Nullable: true},
		{Name: "has_spouse", Type: field.TypeBool, Default: false},
		{Name: "is_baptized", Type: field.TypeBool, Default: false},
		{Name: "baptized_by", Type: field.TypeString, Nullable: true},
		{Name: "baptism_church", Type: field.TypeString, Nullable: true},
		{Name: "baptism_cert_number", Type: field.TypeString, Nullable: true},
		{Name: "baptism_date", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "spouse_id", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "contacts_contacts_spouse_contact",
				Columns:    []*schema.Column{ContactsColumns[35]},
				RefColumns: []*schema.Column{ContactsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "department_type", Type: field.TypeEnum, Enums: []string{"worship", "youth", "children", "outreach", "administration", "finance", "media"}},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "church_departments", Type: field.TypeInt},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:       "departments",
		Columns:    DepartmentsColumns,
		PrimaryKey: []*schema.Column{DepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "departments_churches_departments",
				Columns:    []*schema.Column{DepartmentsColumns[5]},
				RefColumns: []*schema.Column{ChurchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
		{Name: "location", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeEnum, Enums: []string{"service", "meeting", "conference", "outreach", "training"}},
		{Name: "attendance_count", Type: field.TypeInt, Default: 0},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "church_events", Type: field.TypeInt},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_churches_events",
				Columns:    []*schema.Column{EventsColumns[10]},
				RefColumns: []*schema.Column{ChurchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FinancesColumns holds the columns for the "finances" table.
	FinancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString},
		{Name: "transaction_type", Type: field.TypeEnum, Enums: []string{"donation", "tithe", "offering", "expense", "salary", "other"}},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "transaction_date", Type: field.TypeTime},
		{Name: "category", Type: field.TypeString},
		{Name: "payment_method", Type: field.TypeString, Nullable: true},
		{Name: "reference_number", Type: field.TypeString, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "church_finances", Type: field.TypeInt, Nullable: true},
		{Name: "user_finance_records", Type: field.TypeInt, Nullable: true},
	}
	// FinancesTable holds the schema information for the "finances" table.
	FinancesTable = &schema.Table{
		Name:       "finances",
		Columns:    FinancesColumns,
		PrimaryKey: []*schema.Column{FinancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "finances_churches_finances",
				Columns:    []*schema.Column{FinancesColumns[10]},
				RefColumns: []*schema.Column{ChurchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "finances_users_finance_records",
				Columns:    []*schema.Column{FinancesColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// InvitationsColumns holds the columns for the "invitations" table.
	InvitationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "invitee_email", Type: field.TypeString},
		{Name: "invitee_name", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"branch_admin", "secretary", "records_keeper", "finance_officer", "pastor", "member"}},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "accepted", "expired", "revoked"}, Default: "pending"},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "church_invitations", Type: field.TypeInt},
		{Name: "user_sent_invitations", Type: field.TypeInt, Nullable: true},
	}
	// InvitationsTable holds the schema information for the "invitations" table.
	InvitationsTable = &schema.Table{
		Name:       "invitations",
		Columns:    InvitationsColumns,
		PrimaryKey: []*schema.Column{InvitationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invitations_churches_invitations",
				Columns:    []*schema.Column{InvitationsColumns[9]},
				RefColumns: []*schema.Column{ChurchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "invitations_users_sent_invitations",
				Columns:    []*schema.Column{InvitationsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true, Size: 43},
		{Name: "data", Type: field.TypeBytes},
		{Name: "expiry", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "TIMESTAMP(6)"}},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_expiry",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"super_admin", "branch_admin", "secretary", "records_keeper", "finance_officer", "pastor", "member"}, Default: "member"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "church_users", Type: field.TypeInt, Nullable: true},
		{Name: "contact_user", Type: field.TypeInt, Unique: true},
		{Name: "invitation_accepted_user", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_churches_users",
				Columns:    []*schema.Column{UsersColumns[8]},
				RefColumns: []*schema.Column{ChurchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "users_contacts_user",
				Columns:    []*schema.Column{UsersColumns[9]},
				RefColumns: []*schema.Column{ContactsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "users_invitations_accepted_user",
				Columns:    []*schema.Column{UsersColumns[10]},
				RefColumns: []*schema.Column{InvitationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_role",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnnouncementsTable,
		ChurchesTable,
		ContactsTable,
		DepartmentsTable,
		EventsTable,
		FinancesTable,
		InvitationsTable,
		SessionsTable,
		UsersTable,
	}
)

func init() {
	AnnouncementsTable.ForeignKeys[0].RefTable = ChurchesTable
	AnnouncementsTable.ForeignKeys[1].RefTable = UsersTable
	ChurchesTable.ForeignKeys[0].RefTable = ChurchesTable
	ContactsTable.ForeignKeys[0].RefTable = ContactsTable
	DepartmentsTable.ForeignKeys[0].RefTable = ChurchesTable
	EventsTable.ForeignKeys[0].RefTable = ChurchesTable
	FinancesTable.ForeignKeys[0].RefTable = ChurchesTable
	FinancesTable.ForeignKeys[1].RefTable = UsersTable
	InvitationsTable.ForeignKeys[0].RefTable = ChurchesTable
	InvitationsTable.ForeignKeys[1].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = ChurchesTable
	UsersTable.ForeignKeys[1].RefTable = ContactsTable
	UsersTable.ForeignKeys[2].RefTable = InvitationsTable
}
