// Code generated by ent, DO NOT EDIT.

package budgetline

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ntiGideon/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLTE(FieldID, id))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldCategory, v))
}

// AllocatedAmount applies equality check predicate on the "allocated_amount" field. It's identical to AllocatedAmountEQ.
func AllocatedAmount(v float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldAllocatedAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldCurrency, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldNotes, v))
}

// BudgetID applies equality check predicate on the "budget_id" field. It's identical to BudgetIDEQ.
func BudgetID(v int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldBudgetID, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldContainsFold(FieldCategory, v))
}

// LineTypeEQ applies the EQ predicate on the "line_type" field.
func LineTypeEQ(v LineType) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldLineType, v))
}

// LineTypeNEQ applies the NEQ predicate on the "line_type" field.
func LineTypeNEQ(v LineType) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNEQ(FieldLineType, v))
}

// LineTypeIn applies the In predicate on the "line_type" field.
func LineTypeIn(vs ...LineType) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIn(FieldLineType, vs...))
}

// LineTypeNotIn applies the NotIn predicate on the "line_type" field.
func LineTypeNotIn(vs ...LineType) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotIn(FieldLineType, vs...))
}

// AllocatedAmountEQ applies the EQ predicate on the "allocated_amount" field.
func AllocatedAmountEQ(v float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldAllocatedAmount, v))
}

// AllocatedAmountNEQ applies the NEQ predicate on the "allocated_amount" field.
func AllocatedAmountNEQ(v float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNEQ(FieldAllocatedAmount, v))
}

// AllocatedAmountIn applies the In predicate on the "allocated_amount" field.
func AllocatedAmountIn(vs ...float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIn(FieldAllocatedAmount, vs...))
}

// AllocatedAmountNotIn applies the NotIn predicate on the "allocated_amount" field.
func AllocatedAmountNotIn(vs ...float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotIn(FieldAllocatedAmount, vs...))
}

// AllocatedAmountGT applies the GT predicate on the "allocated_amount" field.
func AllocatedAmountGT(v float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGT(FieldAllocatedAmount, v))
}

// AllocatedAmountGTE applies the GTE predicate on the "allocated_amount" field.
func AllocatedAmountGTE(v float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGTE(FieldAllocatedAmount, v))
}

// AllocatedAmountLT applies the LT predicate on the "allocated_amount" field.
func AllocatedAmountLT(v float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLT(FieldAllocatedAmount, v))
}

// AllocatedAmountLTE applies the LTE predicate on the "allocated_amount" field.
func AllocatedAmountLTE(v float64) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLTE(FieldAllocatedAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldContainsFold(FieldCurrency, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldContainsFold(FieldNotes, v))
}

// BudgetIDEQ applies the EQ predicate on the "budget_id" field.
func BudgetIDEQ(v int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldEQ(FieldBudgetID, v))
}

// BudgetIDNEQ applies the NEQ predicate on the "budget_id" field.
func BudgetIDNEQ(v int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNEQ(FieldBudgetID, v))
}

// BudgetIDIn applies the In predicate on the "budget_id" field.
func BudgetIDIn(vs ...int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldIn(FieldBudgetID, vs...))
}

// BudgetIDNotIn applies the NotIn predicate on the "budget_id" field.
func BudgetIDNotIn(vs ...int) predicate.BudgetLine {
	return predicate.BudgetLine(sql.FieldNotIn(FieldBudgetID, vs...))
}

// HasBudget applies the HasEdge predicate on the "budget" edge.
func HasBudget() predicate.BudgetLine {
	return predicate.BudgetLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BudgetTable, BudgetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBudgetWith applies the HasEdge predicate on the "budget" edge with a given conditions (other predicates).
func HasBudgetWith(preds ...predicate.Budget) predicate.BudgetLine {
	return predicate.BudgetLine(func(s *sql.Selector) {
		step := newBudgetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BudgetLine) predicate.BudgetLine {
	return predicate.BudgetLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BudgetLine) predicate.BudgetLine {
	return predicate.BudgetLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BudgetLine) predicate.BudgetLine {
	return predicate.BudgetLine(sql.NotPredicates(p))
}
