// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ntiGideon/ent/budget"
	"github.com/ntiGideon/ent/church"
)

// Budget is the model entity for the Budget schema.
type Budget struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// FiscalYear holds the value of the "fiscal_year" field.
	FiscalYear int `json:"fiscal_year,omitempty"`
	// Period holds the value of the "period" field.
	Period budget.Period `json:"period,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate time.Time `json:"end_date,omitempty"`
	// Status holds the value of the "status" field.
	Status budget.Status `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// ChurchID holds the value of the "church_id" field.
	ChurchID int `json:"church_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BudgetQuery when eager-loading is set.
	Edges        BudgetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BudgetEdges holds the relations/edges for other nodes in the graph.
type BudgetEdges struct {
	// Church holds the value of the church edge.
	Church *Church `json:"church,omitempty"`
	// Lines holds the value of the lines edge.
	Lines []*BudgetLine `json:"lines,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChurchOrErr returns the Church value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BudgetEdges) ChurchOrErr() (*Church, error) {
	if e.Church != nil {
		return e.Church, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: church.Label}
	}
	return nil, &NotLoadedError{edge: "church"}
}

// LinesOrErr returns the Lines value or an error if the edge
// was not loaded in eager-loading.
func (e BudgetEdges) LinesOrErr() ([]*BudgetLine, error) {
	if e.loadedTypes[1] {
		return e.Lines, nil
	}
	return nil, &NotLoadedError{edge: "lines"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Budget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case budget.FieldID, budget.FieldFiscalYear, budget.FieldChurchID:
			values[i] = new(sql.NullInt64)
		case budget.FieldName, budget.FieldPeriod, budget.FieldStatus, budget.FieldNotes:
			values[i] = new(sql.NullString)
		case budget.FieldStartDate, budget.FieldEndDate, budget.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Budget fields.
func (_m *Budget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case budget.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case budget.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case budget.FieldFiscalYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fiscal_year", values[i])
			} else if value.Valid {
				_m.FiscalYear = int(value.Int64)
			}
		case budget.FieldPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				_m.Period = budget.Period(value.String)
			}
		case budget.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case budget.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = value.Time
			}
		case budget.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = budget.Status(value.String)
			}
		case budget.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case budget.FieldChurchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field church_id", values[i])
			} else if value.Valid {
				_m.ChurchID = int(value.Int64)
			}
		case budget.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Budget.
// This includes values selected through modifiers, order, etc.
func (_m *Budget) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChurch queries the "church" edge of the Budget entity.
func (_m *Budget) QueryChurch() *ChurchQuery {
	return NewBudgetClient(_m.config).QueryChurch(_m)
}

// QueryLines queries the "lines" edge of the Budget entity.
func (_m *Budget) QueryLines() *BudgetLineQuery {
	return NewBudgetClient(_m.config).QueryLines(_m)
}

// Update returns a builder for updating this Budget.
// Note that you need to call Budget.Unwrap() before calling this method if this Budget
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Budget) Update() *BudgetUpdateOne {
	return NewBudgetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Budget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Budget) Unwrap() *Budget {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Budget is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Budget) String() string {
	var builder strings.Builder
	builder.WriteString("Budget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("fiscal_year=")
	builder.WriteString(fmt.Sprintf("%v", _m.FiscalYear))
	builder.WriteString(", ")
	builder.WriteString("period=")
	builder.WriteString(fmt.Sprintf("%v", _m.Period))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_date=")
	builder.WriteString(_m.EndDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("church_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChurchID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Budgets is a parsable slice of Budget.
type Budgets []*Budget
