// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ntiGideon/ent/church"
)

// Church is the model entity for the Church schema.
type Church struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// City holds the value of the "city" field.
	City string `json:"city,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// ZipCode holds the value of the "zip_code" field.
	ZipCode string `json:"zip_code,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// Website holds the value of the "website" field.
	Website string `json:"website,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// RegistrationToken holds the value of the "registration_token" field.
	RegistrationToken *string `json:"registration_token,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// EstablishedDate holds the value of the "established_date" field.
	EstablishedDate time.Time `json:"established_date,omitempty"`
	// Type holds the value of the "type" field.
	Type church.Type `json:"type,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID int `json:"parent_id,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude float64 `json:"latitude,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude float64 `json:"longitude,omitempty"`
	// LogoURL holds the value of the "logo_url" field.
	LogoURL string `json:"logo_url,omitempty"`
	// BannerURL holds the value of the "banner_url" field.
	BannerURL string `json:"banner_url,omitempty"`
	// CongregationSize holds the value of the "congregation_size" field.
	CongregationSize int `json:"congregation_size,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChurchQuery when eager-loading is set.
	Edges        ChurchEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChurchEdges holds the relations/edges for other nodes in the graph.
type ChurchEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Church `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Church `json:"children,omitempty"`
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Departments holds the value of the departments edge.
	Departments []*Department `json:"departments,omitempty"`
	// Events holds the value of the events edge.
	Events []*Event `json:"events,omitempty"`
	// Finances holds the value of the finances edge.
	Finances []*Finance `json:"finances,omitempty"`
	// Invitations holds the value of the invitations edge.
	Invitations []*Invitation `json:"invitations,omitempty"`
	// Announcements holds the value of the announcements edge.
	Announcements []*Announcement `json:"announcements,omitempty"`
	// Contacts holds the value of the contacts edge.
	Contacts []*Contact `json:"contacts,omitempty"`
	// Programs holds the value of the programs edge.
	Programs []*ProgramEntry `json:"programs,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// Pledges holds the value of the pledges edge.
	Pledges []*Pledge `json:"pledges,omitempty"`
	// Rosters holds the value of the rosters edge.
	Rosters []*Roster `json:"rosters,omitempty"`
	// Sermons holds the value of the sermons edge.
	Sermons []*Sermon `json:"sermons,omitempty"`
	// Visitors holds the value of the visitors edge.
	Visitors []*Visitor `json:"visitors,omitempty"`
	// PrayerRequests holds the value of the prayer_requests edge.
	PrayerRequests []*PrayerRequest `json:"prayer_requests,omitempty"`
	// Documents holds the value of the documents edge.
	Documents []*Document `json:"documents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [17]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChurchEdges) ParentOrErr() (*Church, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: church.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) ChildrenOrErr() ([]*Church, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// DepartmentsOrErr returns the Departments value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) DepartmentsOrErr() ([]*Department, error) {
	if e.loadedTypes[3] {
		return e.Departments, nil
	}
	return nil, &NotLoadedError{edge: "departments"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[4] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// FinancesOrErr returns the Finances value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) FinancesOrErr() ([]*Finance, error) {
	if e.loadedTypes[5] {
		return e.Finances, nil
	}
	return nil, &NotLoadedError{edge: "finances"}
}

// InvitationsOrErr returns the Invitations value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) InvitationsOrErr() ([]*Invitation, error) {
	if e.loadedTypes[6] {
		return e.Invitations, nil
	}
	return nil, &NotLoadedError{edge: "invitations"}
}

// AnnouncementsOrErr returns the Announcements value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) AnnouncementsOrErr() ([]*Announcement, error) {
	if e.loadedTypes[7] {
		return e.Announcements, nil
	}
	return nil, &NotLoadedError{edge: "announcements"}
}

// ContactsOrErr returns the Contacts value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) ContactsOrErr() ([]*Contact, error) {
	if e.loadedTypes[8] {
		return e.Contacts, nil
	}
	return nil, &NotLoadedError{edge: "contacts"}
}

// ProgramsOrErr returns the Programs value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) ProgramsOrErr() ([]*ProgramEntry, error) {
	if e.loadedTypes[9] {
		return e.Programs, nil
	}
	return nil, &NotLoadedError{edge: "programs"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[10] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// PledgesOrErr returns the Pledges value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) PledgesOrErr() ([]*Pledge, error) {
	if e.loadedTypes[11] {
		return e.Pledges, nil
	}
	return nil, &NotLoadedError{edge: "pledges"}
}

// RostersOrErr returns the Rosters value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) RostersOrErr() ([]*Roster, error) {
	if e.loadedTypes[12] {
		return e.Rosters, nil
	}
	return nil, &NotLoadedError{edge: "rosters"}
}

// SermonsOrErr returns the Sermons value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) SermonsOrErr() ([]*Sermon, error) {
	if e.loadedTypes[13] {
		return e.Sermons, nil
	}
	return nil, &NotLoadedError{edge: "sermons"}
}

// VisitorsOrErr returns the Visitors value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) VisitorsOrErr() ([]*Visitor, error) {
	if e.loadedTypes[14] {
		return e.Visitors, nil
	}
	return nil, &NotLoadedError{edge: "visitors"}
}

// PrayerRequestsOrErr returns the PrayerRequests value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) PrayerRequestsOrErr() ([]*PrayerRequest, error) {
	if e.loadedTypes[15] {
		return e.PrayerRequests, nil
	}
	return nil, &NotLoadedError{edge: "prayer_requests"}
}

// DocumentsOrErr returns the Documents value or an error if the edge
// was not loaded in eager-loading.
func (e ChurchEdges) DocumentsOrErr() ([]*Document, error) {
	if e.loadedTypes[16] {
		return e.Documents, nil
	}
	return nil, &NotLoadedError{edge: "documents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Church) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case church.FieldIsActive:
			values[i] = new(sql.NullBool)
		case church.FieldLatitude, church.FieldLongitude:
			values[i] = new(sql.NullFloat64)
		case church.FieldID, church.FieldParentID, church.FieldCongregationSize:
			values[i] = new(sql.NullInt64)
		case church.FieldName, church.FieldAddress, church.FieldCity, church.FieldState, church.FieldZipCode, church.FieldCountry, church.FieldWebsite, church.FieldPhone, church.FieldRegistrationToken, church.FieldEmail, church.FieldType, church.FieldLogoURL, church.FieldBannerURL:
			values[i] = new(sql.NullString)
		case church.FieldEstablishedDate, church.FieldCreatedAt, church.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Church fields.
func (_m *Church) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case church.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case church.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case church.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case church.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				_m.City = value.String
			}
		case church.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case church.FieldZipCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zip_code", values[i])
			} else if value.Valid {
				_m.ZipCode = value.String
			}
		case church.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case church.FieldWebsite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website", values[i])
			} else if value.Valid {
				_m.Website = value.String
			}
		case church.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case church.FieldRegistrationToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registration_token", values[i])
			} else if value.Valid {
				_m.RegistrationToken = new(string)
				*_m.RegistrationToken = value.String
			}
		case church.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case church.FieldEstablishedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field established_date", values[i])
			} else if value.Valid {
				_m.EstablishedDate = value.Time
			}
		case church.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = church.Type(value.String)
			}
		case church.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = int(value.Int64)
			}
		case church.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				_m.Latitude = value.Float64
			}
		case church.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				_m.Longitude = value.Float64
			}
		case church.FieldLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_url", values[i])
			} else if value.Valid {
				_m.LogoURL = value.String
			}
		case church.FieldBannerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field banner_url", values[i])
			} else if value.Valid {
				_m.BannerURL = value.String
			}
		case church.FieldCongregationSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field congregation_size", values[i])
			} else if value.Valid {
				_m.CongregationSize = int(value.Int64)
			}
		case church.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case church.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case church.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Church.
// This includes values selected through modifiers, order, etc.
func (_m *Church) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the Church entity.
func (_m *Church) QueryParent() *ChurchQuery {
	return NewChurchClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Church entity.
func (_m *Church) QueryChildren() *ChurchQuery {
	return NewChurchClient(_m.config).QueryChildren(_m)
}

// QueryUsers queries the "users" edge of the Church entity.
func (_m *Church) QueryUsers() *UserQuery {
	return NewChurchClient(_m.config).QueryUsers(_m)
}

// QueryDepartments queries the "departments" edge of the Church entity.
func (_m *Church) QueryDepartments() *DepartmentQuery {
	return NewChurchClient(_m.config).QueryDepartments(_m)
}

// QueryEvents queries the "events" edge of the Church entity.
func (_m *Church) QueryEvents() *EventQuery {
	return NewChurchClient(_m.config).QueryEvents(_m)
}

// QueryFinances queries the "finances" edge of the Church entity.
func (_m *Church) QueryFinances() *FinanceQuery {
	return NewChurchClient(_m.config).QueryFinances(_m)
}

// QueryInvitations queries the "invitations" edge of the Church entity.
func (_m *Church) QueryInvitations() *InvitationQuery {
	return NewChurchClient(_m.config).QueryInvitations(_m)
}

// QueryAnnouncements queries the "announcements" edge of the Church entity.
func (_m *Church) QueryAnnouncements() *AnnouncementQuery {
	return NewChurchClient(_m.config).QueryAnnouncements(_m)
}

// QueryContacts queries the "contacts" edge of the Church entity.
func (_m *Church) QueryContacts() *ContactQuery {
	return NewChurchClient(_m.config).QueryContacts(_m)
}

// QueryPrograms queries the "programs" edge of the Church entity.
func (_m *Church) QueryPrograms() *ProgramEntryQuery {
	return NewChurchClient(_m.config).QueryPrograms(_m)
}

// QueryGroups queries the "groups" edge of the Church entity.
func (_m *Church) QueryGroups() *GroupQuery {
	return NewChurchClient(_m.config).QueryGroups(_m)
}

// QueryPledges queries the "pledges" edge of the Church entity.
func (_m *Church) QueryPledges() *PledgeQuery {
	return NewChurchClient(_m.config).QueryPledges(_m)
}

// QueryRosters queries the "rosters" edge of the Church entity.
func (_m *Church) QueryRosters() *RosterQuery {
	return NewChurchClient(_m.config).QueryRosters(_m)
}

// QuerySermons queries the "sermons" edge of the Church entity.
func (_m *Church) QuerySermons() *SermonQuery {
	return NewChurchClient(_m.config).QuerySermons(_m)
}

// QueryVisitors queries the "visitors" edge of the Church entity.
func (_m *Church) QueryVisitors() *VisitorQuery {
	return NewChurchClient(_m.config).QueryVisitors(_m)
}

// QueryPrayerRequests queries the "prayer_requests" edge of the Church entity.
func (_m *Church) QueryPrayerRequests() *PrayerRequestQuery {
	return NewChurchClient(_m.config).QueryPrayerRequests(_m)
}

// QueryDocuments queries the "documents" edge of the Church entity.
func (_m *Church) QueryDocuments() *DocumentQuery {
	return NewChurchClient(_m.config).QueryDocuments(_m)
}

// Update returns a builder for updating this Church.
// Note that you need to call Church.Unwrap() before calling this method if this Church
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Church) Update() *ChurchUpdateOne {
	return NewChurchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Church entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Church) Unwrap() *Church {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Church is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Church) String() string {
	var builder strings.Builder
	builder.WriteString("Church(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(_m.City)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("zip_code=")
	builder.WriteString(_m.ZipCode)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("website=")
	builder.WriteString(_m.Website)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	if v := _m.RegistrationToken; v != nil {
		builder.WriteString("registration_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("established_date=")
	builder.WriteString(_m.EstablishedDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("latitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Latitude))
	builder.WriteString(", ")
	builder.WriteString("longitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Longitude))
	builder.WriteString(", ")
	builder.WriteString("logo_url=")
	builder.WriteString(_m.LogoURL)
	builder.WriteString(", ")
	builder.WriteString("banner_url=")
	builder.WriteString(_m.BannerURL)
	builder.WriteString(", ")
	builder.WriteString("congregation_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.CongregationSize))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Churches is a parsable slice of Church.
type Churches []*Church
