// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/communication"
	"github.com/ntiGideon/ent/user"
)

// CommunicationCreate is the builder for creating a Communication entity.
type CommunicationCreate struct {
	config
	mutation *CommunicationMutation
	hooks    []Hook
}

// SetSubject sets the "subject" field.
func (_c *CommunicationCreate) SetSubject(v string) *CommunicationCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetBodyHTML sets the "body_html" field.
func (_c *CommunicationCreate) SetBodyHTML(v string) *CommunicationCreate {
	_c.mutation.SetBodyHTML(v)
	return _c
}

// SetRecipientFilter sets the "recipient_filter" field.
func (_c *CommunicationCreate) SetRecipientFilter(v string) *CommunicationCreate {
	_c.mutation.SetRecipientFilter(v)
	return _c
}

// SetNillableRecipientFilter sets the "recipient_filter" field if the given value is not nil.
func (_c *CommunicationCreate) SetNillableRecipientFilter(v *string) *CommunicationCreate {
	if v != nil {
		_c.SetRecipientFilter(*v)
	}
	return _c
}

// SetRecipientFilterLabel sets the "recipient_filter_label" field.
func (_c *CommunicationCreate) SetRecipientFilterLabel(v string) *CommunicationCreate {
	_c.mutation.SetRecipientFilterLabel(v)
	return _c
}

// SetNillableRecipientFilterLabel sets the "recipient_filter_label" field if the given value is not nil.
func (_c *CommunicationCreate) SetNillableRecipientFilterLabel(v *string) *CommunicationCreate {
	if v != nil {
		_c.SetRecipientFilterLabel(*v)
	}
	return _c
}

// SetRecipientCount sets the "recipient_count" field.
func (_c *CommunicationCreate) SetRecipientCount(v int) *CommunicationCreate {
	_c.mutation.SetRecipientCount(v)
	return _c
}

// SetNillableRecipientCount sets the "recipient_count" field if the given value is not nil.
func (_c *CommunicationCreate) SetNillableRecipientCount(v *int) *CommunicationCreate {
	if v != nil {
		_c.SetRecipientCount(*v)
	}
	return _c
}

// SetSentCount sets the "sent_count" field.
func (_c *CommunicationCreate) SetSentCount(v int) *CommunicationCreate {
	_c.mutation.SetSentCount(v)
	return _c
}

// SetNillableSentCount sets the "sent_count" field if the given value is not nil.
func (_c *CommunicationCreate) SetNillableSentCount(v *int) *CommunicationCreate {
	if v != nil {
		_c.SetSentCount(*v)
	}
	return _c
}

// SetFailCount sets the "fail_count" field.
func (_c *CommunicationCreate) SetFailCount(v int) *CommunicationCreate {
	_c.mutation.SetFailCount(v)
	return _c
}

// SetNillableFailCount sets the "fail_count" field if the given value is not nil.
func (_c *CommunicationCreate) SetNillableFailCount(v *int) *CommunicationCreate {
	if v != nil {
		_c.SetFailCount(*v)
	}
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *CommunicationCreate) SetSentAt(v time.Time) *CommunicationCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *CommunicationCreate) SetNillableSentAt(v *time.Time) *CommunicationCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetChurchID sets the "church" edge to the Church entity by ID.
func (_c *CommunicationCreate) SetChurchID(id int) *CommunicationCreate {
	_c.mutation.SetChurchID(id)
	return _c
}

// SetChurch sets the "church" edge to the Church entity.
func (_c *CommunicationCreate) SetChurch(v *Church) *CommunicationCreate {
	return _c.SetChurchID(v.ID)
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (_c *CommunicationCreate) SetSenderID(id int) *CommunicationCreate {
	_c.mutation.SetSenderID(id)
	return _c
}

// SetNillableSenderID sets the "sender" edge to the User entity by ID if the given value is not nil.
func (_c *CommunicationCreate) SetNillableSenderID(id *int) *CommunicationCreate {
	if id != nil {
		_c = _c.SetSenderID(*id)
	}
	return _c
}

// SetSender sets the "sender" edge to the User entity.
func (_c *CommunicationCreate) SetSender(v *User) *CommunicationCreate {
	return _c.SetSenderID(v.ID)
}

// Mutation returns the CommunicationMutation object of the builder.
func (_c *CommunicationCreate) Mutation() *CommunicationMutation {
	return _c.mutation
}

// Save creates the Communication in the database.
func (_c *CommunicationCreate) Save(ctx context.Context) (*Communication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommunicationCreate) SaveX(ctx context.Context) *Communication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommunicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommunicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommunicationCreate) defaults() {
	if _, ok := _c.mutation.RecipientFilter(); !ok {
		v := communication.DefaultRecipientFilter
		_c.mutation.SetRecipientFilter(v)
	}
	if _, ok := _c.mutation.RecipientFilterLabel(); !ok {
		v := communication.DefaultRecipientFilterLabel
		_c.mutation.SetRecipientFilterLabel(v)
	}
	if _, ok := _c.mutation.RecipientCount(); !ok {
		v := communication.DefaultRecipientCount
		_c.mutation.SetRecipientCount(v)
	}
	if _, ok := _c.mutation.SentCount(); !ok {
		v := communication.DefaultSentCount
		_c.mutation.SetSentCount(v)
	}
	if _, ok := _c.mutation.FailCount(); !ok {
		v := communication.DefaultFailCount
		_c.mutation.SetFailCount(v)
	}
	if _, ok := _c.mutation.SentAt(); !ok {
		v := communication.DefaultSentAt()
		_c.mutation.SetSentAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommunicationCreate) check() error {
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Communication.subject"`)}
	}
	if _, ok := _c.mutation.BodyHTML(); !ok {
		return &ValidationError{Name: "body_html", err: errors.New(`ent: missing required field "Communication.body_html"`)}
	}
	if _, ok := _c.mutation.RecipientFilter(); !ok {
		return &ValidationError{Name: "recipient_filter", err: errors.New(`ent: missing required field "Communication.recipient_filter"`)}
	}
	if _, ok := _c.mutation.RecipientFilterLabel(); !ok {
		return &ValidationError{Name: "recipient_filter_label", err: errors.New(`ent: missing required field "Communication.recipient_filter_label"`)}
	}
	if _, ok := _c.mutation.RecipientCount(); !ok {
		return &ValidationError{Name: "recipient_count", err: errors.New(`ent: missing required field "Communication.recipient_count"`)}
	}
	if _, ok := _c.mutation.SentCount(); !ok {
		return &ValidationError{Name: "sent_count", err: errors.New(`ent: missing required field "Communication.sent_count"`)}
	}
	if _, ok := _c.mutation.FailCount(); !ok {
		return &ValidationError{Name: "fail_count", err: errors.New(`ent: missing required field "Communication.fail_count"`)}
	}
	if _, ok := _c.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sent_at", err: errors.New(`ent: missing required field "Communication.sent_at"`)}
	}
	if len(_c.mutation.ChurchIDs()) == 0 {
		return &ValidationError{Name: "church", err: errors.New(`ent: missing required edge "Communication.church"`)}
	}
	return nil
}

func (_c *CommunicationCreate) sqlSave(ctx context.Context) (*Communication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommunicationCreate) createSpec() (*Communication, *sqlgraph.CreateSpec) {
	var (
		_node = &Communication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(communication.Table, sqlgraph.NewFieldSpec(communication.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(communication.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.BodyHTML(); ok {
		_spec.SetField(communication.FieldBodyHTML, field.TypeString, value)
		_node.BodyHTML = value
	}
	if value, ok := _c.mutation.RecipientFilter(); ok {
		_spec.SetField(communication.FieldRecipientFilter, field.TypeString, value)
		_node.RecipientFilter = value
	}
	if value, ok := _c.mutation.RecipientFilterLabel(); ok {
		_spec.SetField(communication.FieldRecipientFilterLabel, field.TypeString, value)
		_node.RecipientFilterLabel = value
	}
	if value, ok := _c.mutation.RecipientCount(); ok {
		_spec.SetField(communication.FieldRecipientCount, field.TypeInt, value)
		_node.RecipientCount = value
	}
	if value, ok := _c.mutation.SentCount(); ok {
		_spec.SetField(communication.FieldSentCount, field.TypeInt, value)
		_node.SentCount = value
	}
	if value, ok := _c.mutation.FailCount(); ok {
		_spec.SetField(communication.FieldFailCount, field.TypeInt, value)
		_node.FailCount = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(communication.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if nodes := _c.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   communication.ChurchTable,
			Columns: []string{communication.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.church_communications = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   communication.SenderTable,
			Columns: []string{communication.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_sent_communications = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommunicationCreateBulk is the builder for creating many Communication entities in bulk.
type CommunicationCreateBulk struct {
	config
	err      error
	builders []*CommunicationCreate
}

// Save creates the Communication entities in the database.
func (_c *CommunicationCreateBulk) Save(ctx context.Context) ([]*Communication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Communication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommunicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommunicationCreateBulk) SaveX(ctx context.Context) []*Communication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommunicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommunicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
