// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/user"
)

// ContactCreate is the builder for creating a Contact entity.
type ContactCreate struct {
	config
	mutation *ContactMutation
	hooks    []Hook
}

// SetFirstName sets the "first_name" field.
func (_c *ContactCreate) SetFirstName(v string) *ContactCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetLastName sets the "last_name" field.
func (_c *ContactCreate) SetLastName(v string) *ContactCreate {
	_c.mutation.SetLastName(v)
	return _c
}

// SetMiddleName sets the "middle_name" field.
func (_c *ContactCreate) SetMiddleName(v string) *ContactCreate {
	_c.mutation.SetMiddleName(v)
	return _c
}

// SetNillableMiddleName sets the "middle_name" field if the given value is not nil.
func (_c *ContactCreate) SetNillableMiddleName(v *string) *ContactCreate {
	if v != nil {
		_c.SetMiddleName(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *ContactCreate) SetPhone(v string) *ContactCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *ContactCreate) SetNillablePhone(v *string) *ContactCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetSecondaryPhone sets the "secondary_phone" field.
func (_c *ContactCreate) SetSecondaryPhone(v string) *ContactCreate {
	_c.mutation.SetSecondaryPhone(v)
	return _c
}

// SetNillableSecondaryPhone sets the "secondary_phone" field if the given value is not nil.
func (_c *ContactCreate) SetNillableSecondaryPhone(v *string) *ContactCreate {
	if v != nil {
		_c.SetSecondaryPhone(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *ContactCreate) SetEmail(v string) *ContactCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *ContactCreate) SetNillableEmail(v *string) *ContactCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetGender sets the "gender" field.
func (_c *ContactCreate) SetGender(v contact.Gender) *ContactCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_c *ContactCreate) SetNillableGender(v *contact.Gender) *ContactCreate {
	if v != nil {
		_c.SetGender(*v)
	}
	return _c
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_c *ContactCreate) SetDateOfBirth(v time.Time) *ContactCreate {
	_c.mutation.SetDateOfBirth(v)
	return _c
}

// SetNillableDateOfBirth sets the "date_of_birth" field if the given value is not nil.
func (_c *ContactCreate) SetNillableDateOfBirth(v *time.Time) *ContactCreate {
	if v != nil {
		_c.SetDateOfBirth(*v)
	}
	return _c
}

// SetMaritalStatus sets the "marital_status" field.
func (_c *ContactCreate) SetMaritalStatus(v contact.MaritalStatus) *ContactCreate {
	_c.mutation.SetMaritalStatus(v)
	return _c
}

// SetNillableMaritalStatus sets the "marital_status" field if the given value is not nil.
func (_c *ContactCreate) SetNillableMaritalStatus(v *contact.MaritalStatus) *ContactCreate {
	if v != nil {
		_c.SetMaritalStatus(*v)
	}
	return _c
}

// SetOccupation sets the "occupation" field.
func (_c *ContactCreate) SetOccupation(v string) *ContactCreate {
	_c.mutation.SetOccupation(v)
	return _c
}

// SetNillableOccupation sets the "occupation" field if the given value is not nil.
func (_c *ContactCreate) SetNillableOccupation(v *string) *ContactCreate {
	if v != nil {
		_c.SetOccupation(*v)
	}
	return _c
}

// SetAddressLine1 sets the "address_line1" field.
func (_c *ContactCreate) SetAddressLine1(v string) *ContactCreate {
	_c.mutation.SetAddressLine1(v)
	return _c
}

// SetNillableAddressLine1 sets the "address_line1" field if the given value is not nil.
func (_c *ContactCreate) SetNillableAddressLine1(v *string) *ContactCreate {
	if v != nil {
		_c.SetAddressLine1(*v)
	}
	return _c
}

// SetAddressLine2 sets the "address_line2" field.
func (_c *ContactCreate) SetAddressLine2(v string) *ContactCreate {
	_c.mutation.SetAddressLine2(v)
	return _c
}

// SetNillableAddressLine2 sets the "address_line2" field if the given value is not nil.
func (_c *ContactCreate) SetNillableAddressLine2(v *string) *ContactCreate {
	if v != nil {
		_c.SetAddressLine2(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *ContactCreate) SetCity(v string) *ContactCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *ContactCreate) SetNillableCity(v *string) *ContactCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *ContactCreate) SetState(v string) *ContactCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ContactCreate) SetNillableState(v *string) *ContactCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *ContactCreate) SetCountry(v string) *ContactCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *ContactCreate) SetNillableCountry(v *string) *ContactCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetPostalCode sets the "postal_code" field.
func (_c *ContactCreate) SetPostalCode(v string) *ContactCreate {
	_c.mutation.SetPostalCode(v)
	return _c
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_c *ContactCreate) SetNillablePostalCode(v *string) *ContactCreate {
	if v != nil {
		_c.SetPostalCode(*v)
	}
	return _c
}

// SetEmergencyContactName sets the "emergency_contact_name" field.
func (_c *ContactCreate) SetEmergencyContactName(v string) *ContactCreate {
	_c.mutation.SetEmergencyContactName(v)
	return _c
}

// SetNillableEmergencyContactName sets the "emergency_contact_name" field if the given value is not nil.
func (_c *ContactCreate) SetNillableEmergencyContactName(v *string) *ContactCreate {
	if v != nil {
		_c.SetEmergencyContactName(*v)
	}
	return _c
}

// SetEmergencyContactPhone sets the "emergency_contact_phone" field.
func (_c *ContactCreate) SetEmergencyContactPhone(v string) *ContactCreate {
	_c.mutation.SetEmergencyContactPhone(v)
	return _c
}

// SetNillableEmergencyContactPhone sets the "emergency_contact_phone" field if the given value is not nil.
func (_c *ContactCreate) SetNillableEmergencyContactPhone(v *string) *ContactCreate {
	if v != nil {
		_c.SetEmergencyContactPhone(*v)
	}
	return _c
}

// SetEmergencyContactRelationship sets the "emergency_contact_relationship" field.
func (_c *ContactCreate) SetEmergencyContactRelationship(v string) *ContactCreate {
	_c.mutation.SetEmergencyContactRelationship(v)
	return _c
}

// SetNillableEmergencyContactRelationship sets the "emergency_contact_relationship" field if the given value is not nil.
func (_c *ContactCreate) SetNillableEmergencyContactRelationship(v *string) *ContactCreate {
	if v != nil {
		_c.SetEmergencyContactRelationship(*v)
	}
	return _c
}

// SetProfilePictureURL sets the "profile_picture_url" field.
func (_c *ContactCreate) SetProfilePictureURL(v string) *ContactCreate {
	_c.mutation.SetProfilePictureURL(v)
	return _c
}

// SetNillableProfilePictureURL sets the "profile_picture_url" field if the given value is not nil.
func (_c *ContactCreate) SetNillableProfilePictureURL(v *string) *ContactCreate {
	if v != nil {
		_c.SetProfilePictureURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContactCreate) SetCreatedAt(v time.Time) *ContactCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContactCreate) SetNillableCreatedAt(v *time.Time) *ContactCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContactCreate) SetUpdatedAt(v time.Time) *ContactCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContactCreate) SetNillableUpdatedAt(v *time.Time) *ContactCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ContactCreate) SetUserID(id int) *ContactCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *ContactCreate) SetNillableUserID(id *int) *ContactCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ContactCreate) SetUser(v *User) *ContactCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ContactMutation object of the builder.
func (_c *ContactCreate) Mutation() *ContactMutation {
	return _c.mutation
}

// Save creates the Contact in the database.
func (_c *ContactCreate) Save(ctx context.Context) (*Contact, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContactCreate) SaveX(ctx context.Context) *Contact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContactCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContactCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContactCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contact.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := contact.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContactCreate) check() error {
	if _, ok := _c.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Contact.first_name"`)}
	}
	if _, ok := _c.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Contact.last_name"`)}
	}
	if v, ok := _c.mutation.Gender(); ok {
		if err := contact.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Contact.gender": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MaritalStatus(); ok {
		if err := contact.MaritalStatusValidator(v); err != nil {
			return &ValidationError{Name: "marital_status", err: fmt.Errorf(`ent: validator failed for field "Contact.marital_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Contact.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Contact.updated_at"`)}
	}
	return nil
}

func (_c *ContactCreate) sqlSave(ctx context.Context) (*Contact, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContactCreate) createSpec() (*Contact, *sqlgraph.CreateSpec) {
	var (
		_node = &Contact{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contact.Table, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(contact.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := _c.mutation.LastName(); ok {
		_spec.SetField(contact.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := _c.mutation.MiddleName(); ok {
		_spec.SetField(contact.FieldMiddleName, field.TypeString, value)
		_node.MiddleName = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(contact.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.SecondaryPhone(); ok {
		_spec.SetField(contact.FieldSecondaryPhone, field.TypeString, value)
		_node.SecondaryPhone = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(contact.FieldGender, field.TypeEnum, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.DateOfBirth(); ok {
		_spec.SetField(contact.FieldDateOfBirth, field.TypeTime, value)
		_node.DateOfBirth = value
	}
	if value, ok := _c.mutation.MaritalStatus(); ok {
		_spec.SetField(contact.FieldMaritalStatus, field.TypeEnum, value)
		_node.MaritalStatus = value
	}
	if value, ok := _c.mutation.Occupation(); ok {
		_spec.SetField(contact.FieldOccupation, field.TypeString, value)
		_node.Occupation = value
	}
	if value, ok := _c.mutation.AddressLine1(); ok {
		_spec.SetField(contact.FieldAddressLine1, field.TypeString, value)
		_node.AddressLine1 = value
	}
	if value, ok := _c.mutation.AddressLine2(); ok {
		_spec.SetField(contact.FieldAddressLine2, field.TypeString, value)
		_node.AddressLine2 = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(contact.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(contact.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(contact.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.PostalCode(); ok {
		_spec.SetField(contact.FieldPostalCode, field.TypeString, value)
		_node.PostalCode = value
	}
	if value, ok := _c.mutation.EmergencyContactName(); ok {
		_spec.SetField(contact.FieldEmergencyContactName, field.TypeString, value)
		_node.EmergencyContactName = value
	}
	if value, ok := _c.mutation.EmergencyContactPhone(); ok {
		_spec.SetField(contact.FieldEmergencyContactPhone, field.TypeString, value)
		_node.EmergencyContactPhone = value
	}
	if value, ok := _c.mutation.EmergencyContactRelationship(); ok {
		_spec.SetField(contact.FieldEmergencyContactRelationship, field.TypeString, value)
		_node.EmergencyContactRelationship = value
	}
	if value, ok := _c.mutation.ProfilePictureURL(); ok {
		_spec.SetField(contact.FieldProfilePictureURL, field.TypeString, value)
		_node.ProfilePictureURL = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contact.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contact.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   contact.UserTable,
			Columns: []string{contact.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ContactCreateBulk is the builder for creating many Contact entities in bulk.
type ContactCreateBulk struct {
	config
	err      error
	builders []*ContactCreate
}

// Save creates the Contact entities in the database.
func (_c *ContactCreateBulk) Save(ctx context.Context) ([]*Contact, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Contact, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContactCreateBulk) SaveX(ctx context.Context) []*Contact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContactCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContactCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
