// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/attendance"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/department"
	"github.com/ntiGideon/ent/finance"
	"github.com/ntiGideon/ent/group"
	"github.com/ntiGideon/ent/milestone"
	"github.com/ntiGideon/ent/pastoralnote"
	"github.com/ntiGideon/ent/pledge"
	"github.com/ntiGideon/ent/prayerrequest"
	"github.com/ntiGideon/ent/predicate"
	"github.com/ntiGideon/ent/relationship"
	"github.com/ntiGideon/ent/rosterentry"
	"github.com/ntiGideon/ent/user"
)

// ContactQuery is the builder for querying Contact entities.
type ContactQuery struct {
	config
	ctx                    *QueryContext
	order                  []contact.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Contact
	withUser               *UserQuery
	withChurch             *ChurchQuery
	withSpouseContact      *ContactQuery
	withSpouseOfContact    *ContactQuery
	withAttendances        *AttendanceQuery
	withGroups             *GroupQuery
	withLeadingGroups      *GroupQuery
	withGivingRecords      *FinanceQuery
	withPledges            *PledgeQuery
	withRosterEntries      *RosterEntryQuery
	withPrayerRequests     *PrayerRequestQuery
	withPastoralNotes      *PastoralNoteQuery
	withMilestones         *MilestoneQuery
	withDepartments        *DepartmentQuery
	withLeadingDepartments *DepartmentQuery
	withRelationshipsFrom  *RelationshipQuery
	withRelationshipsTo    *RelationshipQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContactQuery builder.
func (_q *ContactQuery) Where(ps ...predicate.Contact) *ContactQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ContactQuery) Limit(limit int) *ContactQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ContactQuery) Offset(offset int) *ContactQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ContactQuery) Unique(unique bool) *ContactQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ContactQuery) Order(o ...contact.OrderOption) *ContactQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *ContactQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, contact.UserTable, contact.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChurch chains the current query on the "church" edge.
func (_q *ContactQuery) QueryChurch() *ChurchQuery {
	query := (&ChurchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(church.Table, church.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, contact.ChurchTable, contact.ChurchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySpouseContact chains the current query on the "spouse_contact" edge.
func (_q *ContactQuery) QuerySpouseContact() *ContactQuery {
	query := (&ContactClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(contact.Table, contact.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, contact.SpouseContactTable, contact.SpouseContactColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySpouseOfContact chains the current query on the "spouse_of_contact" edge.
func (_q *ContactQuery) QuerySpouseOfContact() *ContactQuery {
	query := (&ContactClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(contact.Table, contact.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, contact.SpouseOfContactTable, contact.SpouseOfContactColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttendances chains the current query on the "attendances" edge.
func (_q *ContactQuery) QueryAttendances() *AttendanceQuery {
	query := (&AttendanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(attendance.Table, attendance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.AttendancesTable, contact.AttendancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroups chains the current query on the "groups" edge.
func (_q *ContactQuery) QueryGroups() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, contact.GroupsTable, contact.GroupsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLeadingGroups chains the current query on the "leading_groups" edge.
func (_q *ContactQuery) QueryLeadingGroups() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, contact.LeadingGroupsTable, contact.LeadingGroupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGivingRecords chains the current query on the "giving_records" edge.
func (_q *ContactQuery) QueryGivingRecords() *FinanceQuery {
	query := (&FinanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(finance.Table, finance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, contact.GivingRecordsTable, contact.GivingRecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPledges chains the current query on the "pledges" edge.
func (_q *ContactQuery) QueryPledges() *PledgeQuery {
	query := (&PledgeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(pledge.Table, pledge.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.PledgesTable, contact.PledgesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRosterEntries chains the current query on the "roster_entries" edge.
func (_q *ContactQuery) QueryRosterEntries() *RosterEntryQuery {
	query := (&RosterEntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(rosterentry.Table, rosterentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.RosterEntriesTable, contact.RosterEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPrayerRequests chains the current query on the "prayer_requests" edge.
func (_q *ContactQuery) QueryPrayerRequests() *PrayerRequestQuery {
	query := (&PrayerRequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(prayerrequest.Table, prayerrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.PrayerRequestsTable, contact.PrayerRequestsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPastoralNotes chains the current query on the "pastoral_notes" edge.
func (_q *ContactQuery) QueryPastoralNotes() *PastoralNoteQuery {
	query := (&PastoralNoteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(pastoralnote.Table, pastoralnote.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.PastoralNotesTable, contact.PastoralNotesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMilestones chains the current query on the "milestones" edge.
func (_q *ContactQuery) QueryMilestones() *MilestoneQuery {
	query := (&MilestoneClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(milestone.Table, milestone.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.MilestonesTable, contact.MilestonesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDepartments chains the current query on the "departments" edge.
func (_q *ContactQuery) QueryDepartments() *DepartmentQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, contact.DepartmentsTable, contact.DepartmentsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLeadingDepartments chains the current query on the "leading_departments" edge.
func (_q *ContactQuery) QueryLeadingDepartments() *DepartmentQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, contact.LeadingDepartmentsTable, contact.LeadingDepartmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelationshipsFrom chains the current query on the "relationships_from" edge.
func (_q *ContactQuery) QueryRelationshipsFrom() *RelationshipQuery {
	query := (&RelationshipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(relationship.Table, relationship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.RelationshipsFromTable, contact.RelationshipsFromColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelationshipsTo chains the current query on the "relationships_to" edge.
func (_q *ContactQuery) QueryRelationshipsTo() *RelationshipQuery {
	query := (&RelationshipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contact.Table, contact.FieldID, selector),
			sqlgraph.To(relationship.Table, relationship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contact.RelationshipsToTable, contact.RelationshipsToColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Contact entity from the query.
// Returns a *NotFoundError when no Contact was found.
func (_q *ContactQuery) First(ctx context.Context) (*Contact, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contact.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ContactQuery) FirstX(ctx context.Context) *Contact {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Contact ID from the query.
// Returns a *NotFoundError when no Contact ID was found.
func (_q *ContactQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contact.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ContactQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Contact entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Contact entity is found.
// Returns a *NotFoundError when no Contact entities are found.
func (_q *ContactQuery) Only(ctx context.Context) (*Contact, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contact.Label}
	default:
		return nil, &NotSingularError{contact.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ContactQuery) OnlyX(ctx context.Context) *Contact {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Contact ID in the query.
// Returns a *NotSingularError when more than one Contact ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ContactQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contact.Label}
	default:
		err = &NotSingularError{contact.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ContactQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Contacts.
func (_q *ContactQuery) All(ctx context.Context) ([]*Contact, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Contact, *ContactQuery]()
	return withInterceptors[[]*Contact](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ContactQuery) AllX(ctx context.Context) []*Contact {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Contact IDs.
func (_q *ContactQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(contact.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ContactQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ContactQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ContactQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ContactQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ContactQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ContactQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContactQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ContactQuery) Clone() *ContactQuery {
	if _q == nil {
		return nil
	}
	return &ContactQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]contact.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.Contact{}, _q.predicates...),
		withUser:               _q.withUser.Clone(),
		withChurch:             _q.withChurch.Clone(),
		withSpouseContact:      _q.withSpouseContact.Clone(),
		withSpouseOfContact:    _q.withSpouseOfContact.Clone(),
		withAttendances:        _q.withAttendances.Clone(),
		withGroups:             _q.withGroups.Clone(),
		withLeadingGroups:      _q.withLeadingGroups.Clone(),
		withGivingRecords:      _q.withGivingRecords.Clone(),
		withPledges:            _q.withPledges.Clone(),
		withRosterEntries:      _q.withRosterEntries.Clone(),
		withPrayerRequests:     _q.withPrayerRequests.Clone(),
		withPastoralNotes:      _q.withPastoralNotes.Clone(),
		withMilestones:         _q.withMilestones.Clone(),
		withDepartments:        _q.withDepartments.Clone(),
		withLeadingDepartments: _q.withLeadingDepartments.Clone(),
		withRelationshipsFrom:  _q.withRelationshipsFrom.Clone(),
		withRelationshipsTo:    _q.withRelationshipsTo.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithUser(opts ...func(*UserQuery)) *ContactQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithChurch tells the query-builder to eager-load the nodes that are connected to
// the "church" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithChurch(opts ...func(*ChurchQuery)) *ContactQuery {
	query := (&ChurchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChurch = query
	return _q
}

// WithSpouseContact tells the query-builder to eager-load the nodes that are connected to
// the "spouse_contact" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithSpouseContact(opts ...func(*ContactQuery)) *ContactQuery {
	query := (&ContactClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSpouseContact = query
	return _q
}

// WithSpouseOfContact tells the query-builder to eager-load the nodes that are connected to
// the "spouse_of_contact" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithSpouseOfContact(opts ...func(*ContactQuery)) *ContactQuery {
	query := (&ContactClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSpouseOfContact = query
	return _q
}

// WithAttendances tells the query-builder to eager-load the nodes that are connected to
// the "attendances" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithAttendances(opts ...func(*AttendanceQuery)) *ContactQuery {
	query := (&AttendanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttendances = query
	return _q
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithGroups(opts ...func(*GroupQuery)) *ContactQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroups = query
	return _q
}

// WithLeadingGroups tells the query-builder to eager-load the nodes that are connected to
// the "leading_groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithLeadingGroups(opts ...func(*GroupQuery)) *ContactQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLeadingGroups = query
	return _q
}

// WithGivingRecords tells the query-builder to eager-load the nodes that are connected to
// the "giving_records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithGivingRecords(opts ...func(*FinanceQuery)) *ContactQuery {
	query := (&FinanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGivingRecords = query
	return _q
}

// WithPledges tells the query-builder to eager-load the nodes that are connected to
// the "pledges" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithPledges(opts ...func(*PledgeQuery)) *ContactQuery {
	query := (&PledgeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPledges = query
	return _q
}

// WithRosterEntries tells the query-builder to eager-load the nodes that are connected to
// the "roster_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithRosterEntries(opts ...func(*RosterEntryQuery)) *ContactQuery {
	query := (&RosterEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRosterEntries = query
	return _q
}

// WithPrayerRequests tells the query-builder to eager-load the nodes that are connected to
// the "prayer_requests" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithPrayerRequests(opts ...func(*PrayerRequestQuery)) *ContactQuery {
	query := (&PrayerRequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPrayerRequests = query
	return _q
}

// WithPastoralNotes tells the query-builder to eager-load the nodes that are connected to
// the "pastoral_notes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithPastoralNotes(opts ...func(*PastoralNoteQuery)) *ContactQuery {
	query := (&PastoralNoteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPastoralNotes = query
	return _q
}

// WithMilestones tells the query-builder to eager-load the nodes that are connected to
// the "milestones" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithMilestones(opts ...func(*MilestoneQuery)) *ContactQuery {
	query := (&MilestoneClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMilestones = query
	return _q
}

// WithDepartments tells the query-builder to eager-load the nodes that are connected to
// the "departments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithDepartments(opts ...func(*DepartmentQuery)) *ContactQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDepartments = query
	return _q
}

// WithLeadingDepartments tells the query-builder to eager-load the nodes that are connected to
// the "leading_departments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithLeadingDepartments(opts ...func(*DepartmentQuery)) *ContactQuery {
	query := (&DepartmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLeadingDepartments = query
	return _q
}

// WithRelationshipsFrom tells the query-builder to eager-load the nodes that are connected to
// the "relationships_from" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithRelationshipsFrom(opts ...func(*RelationshipQuery)) *ContactQuery {
	query := (&RelationshipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRelationshipsFrom = query
	return _q
}

// WithRelationshipsTo tells the query-builder to eager-load the nodes that are connected to
// the "relationships_to" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContactQuery) WithRelationshipsTo(opts ...func(*RelationshipQuery)) *ContactQuery {
	query := (&RelationshipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRelationshipsTo = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Contact.Query().
//		GroupBy(contact.FieldFirstName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ContactQuery) GroupBy(field string, fields ...string) *ContactGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContactGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = contact.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//	}
//
//	client.Contact.Query().
//		Select(contact.FieldFirstName).
//		Scan(ctx, &v)
func (_q *ContactQuery) Select(fields ...string) *ContactSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ContactSelect{ContactQuery: _q}
	sbuild.label = contact.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContactSelect configured with the given aggregations.
func (_q *ContactQuery) Aggregate(fns ...AggregateFunc) *ContactSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ContactQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !contact.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ContactQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Contact, error) {
	var (
		nodes       = []*Contact{}
		_spec       = _q.querySpec()
		loadedTypes = [17]bool{
			_q.withUser != nil,
			_q.withChurch != nil,
			_q.withSpouseContact != nil,
			_q.withSpouseOfContact != nil,
			_q.withAttendances != nil,
			_q.withGroups != nil,
			_q.withLeadingGroups != nil,
			_q.withGivingRecords != nil,
			_q.withPledges != nil,
			_q.withRosterEntries != nil,
			_q.withPrayerRequests != nil,
			_q.withPastoralNotes != nil,
			_q.withMilestones != nil,
			_q.withDepartments != nil,
			_q.withLeadingDepartments != nil,
			_q.withRelationshipsFrom != nil,
			_q.withRelationshipsTo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Contact).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Contact{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *Contact, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChurch; query != nil {
		if err := _q.loadChurch(ctx, query, nodes, nil,
			func(n *Contact, e *Church) { n.Edges.Church = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSpouseContact; query != nil {
		if err := _q.loadSpouseContact(ctx, query, nodes, nil,
			func(n *Contact, e *Contact) { n.Edges.SpouseContact = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSpouseOfContact; query != nil {
		if err := _q.loadSpouseOfContact(ctx, query, nodes, nil,
			func(n *Contact, e *Contact) { n.Edges.SpouseOfContact = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttendances; query != nil {
		if err := _q.loadAttendances(ctx, query, nodes,
			func(n *Contact) { n.Edges.Attendances = []*Attendance{} },
			func(n *Contact, e *Attendance) { n.Edges.Attendances = append(n.Edges.Attendances, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroups; query != nil {
		if err := _q.loadGroups(ctx, query, nodes,
			func(n *Contact) { n.Edges.Groups = []*Group{} },
			func(n *Contact, e *Group) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLeadingGroups; query != nil {
		if err := _q.loadLeadingGroups(ctx, query, nodes,
			func(n *Contact) { n.Edges.LeadingGroups = []*Group{} },
			func(n *Contact, e *Group) { n.Edges.LeadingGroups = append(n.Edges.LeadingGroups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGivingRecords; query != nil {
		if err := _q.loadGivingRecords(ctx, query, nodes,
			func(n *Contact) { n.Edges.GivingRecords = []*Finance{} },
			func(n *Contact, e *Finance) { n.Edges.GivingRecords = append(n.Edges.GivingRecords, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPledges; query != nil {
		if err := _q.loadPledges(ctx, query, nodes,
			func(n *Contact) { n.Edges.Pledges = []*Pledge{} },
			func(n *Contact, e *Pledge) { n.Edges.Pledges = append(n.Edges.Pledges, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRosterEntries; query != nil {
		if err := _q.loadRosterEntries(ctx, query, nodes,
			func(n *Contact) { n.Edges.RosterEntries = []*RosterEntry{} },
			func(n *Contact, e *RosterEntry) { n.Edges.RosterEntries = append(n.Edges.RosterEntries, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPrayerRequests; query != nil {
		if err := _q.loadPrayerRequests(ctx, query, nodes,
			func(n *Contact) { n.Edges.PrayerRequests = []*PrayerRequest{} },
			func(n *Contact, e *PrayerRequest) { n.Edges.PrayerRequests = append(n.Edges.PrayerRequests, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPastoralNotes; query != nil {
		if err := _q.loadPastoralNotes(ctx, query, nodes,
			func(n *Contact) { n.Edges.PastoralNotes = []*PastoralNote{} },
			func(n *Contact, e *PastoralNote) { n.Edges.PastoralNotes = append(n.Edges.PastoralNotes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMilestones; query != nil {
		if err := _q.loadMilestones(ctx, query, nodes,
			func(n *Contact) { n.Edges.Milestones = []*Milestone{} },
			func(n *Contact, e *Milestone) { n.Edges.Milestones = append(n.Edges.Milestones, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDepartments; query != nil {
		if err := _q.loadDepartments(ctx, query, nodes,
			func(n *Contact) { n.Edges.Departments = []*Department{} },
			func(n *Contact, e *Department) { n.Edges.Departments = append(n.Edges.Departments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLeadingDepartments; query != nil {
		if err := _q.loadLeadingDepartments(ctx, query, nodes,
			func(n *Contact) { n.Edges.LeadingDepartments = []*Department{} },
			func(n *Contact, e *Department) { n.Edges.LeadingDepartments = append(n.Edges.LeadingDepartments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRelationshipsFrom; query != nil {
		if err := _q.loadRelationshipsFrom(ctx, query, nodes,
			func(n *Contact) { n.Edges.RelationshipsFrom = []*Relationship{} },
			func(n *Contact, e *Relationship) { n.Edges.RelationshipsFrom = append(n.Edges.RelationshipsFrom, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRelationshipsTo; query != nil {
		if err := _q.loadRelationshipsTo(ctx, query, nodes,
			func(n *Contact) { n.Edges.RelationshipsTo = []*Relationship{} },
			func(n *Contact, e *Relationship) { n.Edges.RelationshipsTo = append(n.Edges.RelationshipsTo, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ContactQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.UserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.contact_user
		if fk == nil {
			return fmt.Errorf(`foreign-key "contact_user" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_user" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadChurch(ctx context.Context, query *ChurchQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Church)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Contact)
	for i := range nodes {
		fk := nodes[i].ChurchID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(church.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "church_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ContactQuery) loadSpouseContact(ctx context.Context, query *ContactQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Contact)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Contact)
	for i := range nodes {
		fk := nodes[i].SpouseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contact.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "spouse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ContactQuery) loadSpouseOfContact(ctx context.Context, query *ContactQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Contact)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Contact)
	for i := range nodes {
		fk := nodes[i].SpouseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contact.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "spouse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ContactQuery) loadAttendances(ctx context.Context, query *AttendanceQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Attendance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(attendance.FieldContactID)
	}
	query.Where(predicate.Attendance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.AttendancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadGroups(ctx context.Context, query *GroupQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Group)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Contact)
	nids := make(map[int]map[*Contact]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(contact.GroupsTable)
		s.Join(joinT).On(s.C(group.FieldID), joinT.C(contact.GroupsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(contact.GroupsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(contact.GroupsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Contact]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Group](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "groups" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *ContactQuery) loadLeadingGroups(ctx context.Context, query *GroupQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Group)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(group.FieldLeaderID)
	}
	query.Where(predicate.Group(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.LeadingGroupsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LeaderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "leader_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadGivingRecords(ctx context.Context, query *FinanceQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Finance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(finance.FieldContactID)
	}
	query.Where(predicate.Finance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.GivingRecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadPledges(ctx context.Context, query *PledgeQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Pledge)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(pledge.FieldContactID)
	}
	query.Where(predicate.Pledge(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.PledgesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadRosterEntries(ctx context.Context, query *RosterEntryQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *RosterEntry)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rosterentry.FieldContactID)
	}
	query.Where(predicate.RosterEntry(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.RosterEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadPrayerRequests(ctx context.Context, query *PrayerRequestQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *PrayerRequest)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(prayerrequest.FieldContactID)
	}
	query.Where(predicate.PrayerRequest(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.PrayerRequestsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadPastoralNotes(ctx context.Context, query *PastoralNoteQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *PastoralNote)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(pastoralnote.FieldContactID)
	}
	query.Where(predicate.PastoralNote(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.PastoralNotesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadMilestones(ctx context.Context, query *MilestoneQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Milestone)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(milestone.FieldContactID)
	}
	query.Where(predicate.Milestone(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.MilestonesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadDepartments(ctx context.Context, query *DepartmentQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Department)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Contact)
	nids := make(map[int]map[*Contact]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(contact.DepartmentsTable)
		s.Join(joinT).On(s.C(department.FieldID), joinT.C(contact.DepartmentsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(contact.DepartmentsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(contact.DepartmentsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Contact]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Department](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "departments" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *ContactQuery) loadLeadingDepartments(ctx context.Context, query *DepartmentQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Department)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(department.FieldLeaderID)
	}
	query.Where(predicate.Department(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.LeadingDepartmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LeaderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "leader_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadRelationshipsFrom(ctx context.Context, query *RelationshipQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Relationship)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(relationship.FieldFromContactID)
	}
	query.Where(predicate.Relationship(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.RelationshipsFromColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FromContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "from_contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContactQuery) loadRelationshipsTo(ctx context.Context, query *RelationshipQuery, nodes []*Contact, init func(*Contact), assign func(*Contact, *Relationship)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Contact)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(relationship.FieldToContactID)
	}
	query.Where(predicate.Relationship(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contact.RelationshipsToColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ToContactID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "to_contact_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ContactQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ContactQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(contact.Table, contact.Columns, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contact.FieldID)
		for i := range fields {
			if fields[i] != contact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChurch != nil {
			_spec.Node.AddColumnOnce(contact.FieldChurchID)
		}
		if _q.withSpouseContact != nil {
			_spec.Node.AddColumnOnce(contact.FieldSpouseID)
		}
		if _q.withSpouseOfContact != nil {
			_spec.Node.AddColumnOnce(contact.FieldSpouseID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ContactQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(contact.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = contact.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContactGroupBy is the group-by builder for Contact entities.
type ContactGroupBy struct {
	selector
	build *ContactQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ContactGroupBy) Aggregate(fns ...AggregateFunc) *ContactGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ContactGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContactQuery, *ContactGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ContactGroupBy) sqlScan(ctx context.Context, root *ContactQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContactSelect is the builder for selecting fields of Contact entities.
type ContactSelect struct {
	*ContactQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ContactSelect) Aggregate(fns ...AggregateFunc) *ContactSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ContactSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContactQuery, *ContactSelect](ctx, _s.ContactQuery, _s, _s.inters, v)
}

func (_s *ContactSelect) sqlScan(ctx context.Context, root *ContactQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
