// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/customrole"
)

// CustomRole is the model entity for the CustomRole schema.
type CustomRole struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Permissions holds the value of the "permissions" field.
	Permissions string `json:"permissions,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// ChurchID holds the value of the "church_id" field.
	ChurchID int `json:"church_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CustomRoleQuery when eager-loading is set.
	Edges        CustomRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CustomRoleEdges holds the relations/edges for other nodes in the graph.
type CustomRoleEdges struct {
	// Church holds the value of the church edge.
	Church *Church `json:"church,omitempty"`
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Invitations holds the value of the invitations edge.
	Invitations []*Invitation `json:"invitations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChurchOrErr returns the Church value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CustomRoleEdges) ChurchOrErr() (*Church, error) {
	if e.Church != nil {
		return e.Church, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: church.Label}
	}
	return nil, &NotLoadedError{edge: "church"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e CustomRoleEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// InvitationsOrErr returns the Invitations value or an error if the edge
// was not loaded in eager-loading.
func (e CustomRoleEdges) InvitationsOrErr() ([]*Invitation, error) {
	if e.loadedTypes[2] {
		return e.Invitations, nil
	}
	return nil, &NotLoadedError{edge: "invitations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case customrole.FieldIsActive:
			values[i] = new(sql.NullBool)
		case customrole.FieldID, customrole.FieldChurchID:
			values[i] = new(sql.NullInt64)
		case customrole.FieldName, customrole.FieldDescription, customrole.FieldPermissions:
			values[i] = new(sql.NullString)
		case customrole.FieldCreatedAt, customrole.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomRole fields.
func (_m *CustomRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case customrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case customrole.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case customrole.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case customrole.FieldPermissions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permissions", values[i])
			} else if value.Valid {
				_m.Permissions = value.String
			}
		case customrole.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case customrole.FieldChurchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field church_id", values[i])
			} else if value.Valid {
				_m.ChurchID = int(value.Int64)
			}
		case customrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case customrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomRole.
// This includes values selected through modifiers, order, etc.
func (_m *CustomRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChurch queries the "church" edge of the CustomRole entity.
func (_m *CustomRole) QueryChurch() *ChurchQuery {
	return NewCustomRoleClient(_m.config).QueryChurch(_m)
}

// QueryUsers queries the "users" edge of the CustomRole entity.
func (_m *CustomRole) QueryUsers() *UserQuery {
	return NewCustomRoleClient(_m.config).QueryUsers(_m)
}

// QueryInvitations queries the "invitations" edge of the CustomRole entity.
func (_m *CustomRole) QueryInvitations() *InvitationQuery {
	return NewCustomRoleClient(_m.config).QueryInvitations(_m)
}

// Update returns a builder for updating this CustomRole.
// Note that you need to call CustomRole.Unwrap() before calling this method if this CustomRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomRole) Update() *CustomRoleUpdateOne {
	return NewCustomRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomRole) Unwrap() *CustomRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomRole) String() string {
	var builder strings.Builder
	builder.WriteString("CustomRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("permissions=")
	builder.WriteString(_m.Permissions)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("church_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChurchID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CustomRoles is a parsable slice of CustomRole.
type CustomRoles []*CustomRole
