// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/department"
	"github.com/ntiGideon/ent/predicate"
)

// DepartmentUpdate is the builder for updating Department entities.
type DepartmentUpdate struct {
	config
	hooks    []Hook
	mutation *DepartmentMutation
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (_u *DepartmentUpdate) Where(ps ...predicate.Department) *DepartmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DepartmentUpdate) SetName(v string) *DepartmentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableName(v *string) *DepartmentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DepartmentUpdate) SetDescription(v string) *DepartmentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableDescription(v *string) *DepartmentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDepartmentType sets the "department_type" field.
func (_u *DepartmentUpdate) SetDepartmentType(v department.DepartmentType) *DepartmentUpdate {
	_u.mutation.SetDepartmentType(v)
	return _u
}

// SetNillableDepartmentType sets the "department_type" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableDepartmentType(v *department.DepartmentType) *DepartmentUpdate {
	if v != nil {
		_u.SetDepartmentType(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DepartmentUpdate) SetIsActive(v bool) *DepartmentUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableIsActive(v *bool) *DepartmentUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetChurchID sets the "church" edge to the Church entity by ID.
func (_u *DepartmentUpdate) SetChurchID(id int) *DepartmentUpdate {
	_u.mutation.SetChurchID(id)
	return _u
}

// SetChurch sets the "church" edge to the Church entity.
func (_u *DepartmentUpdate) SetChurch(v *Church) *DepartmentUpdate {
	return _u.SetChurchID(v.ID)
}

// Mutation returns the DepartmentMutation object of the builder.
func (_u *DepartmentUpdate) Mutation() *DepartmentMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the Church entity.
func (_u *DepartmentUpdate) ClearChurch() *DepartmentUpdate {
	_u.mutation.ClearChurch()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepartmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepartmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepartmentUpdate) check() error {
	if v, ok := _u.mutation.DepartmentType(); ok {
		if err := department.DepartmentTypeValidator(v); err != nil {
			return &ValidationError{Name: "department_type", err: fmt.Errorf(`ent: validator failed for field "Department.department_type": %w`, err)}
		}
	}
	if _u.mutation.ChurchCleared() && len(_u.mutation.ChurchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Department.church"`)
	}
	return nil
}

func (_u *DepartmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DepartmentType(); ok {
		_spec.SetField(department.FieldDepartmentType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(department.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ChurchTable,
			Columns: []string{department.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ChurchTable,
			Columns: []string{department.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepartmentUpdateOne is the builder for updating a single Department entity.
type DepartmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepartmentMutation
}

// SetName sets the "name" field.
func (_u *DepartmentUpdateOne) SetName(v string) *DepartmentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableName(v *string) *DepartmentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DepartmentUpdateOne) SetDescription(v string) *DepartmentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableDescription(v *string) *DepartmentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDepartmentType sets the "department_type" field.
func (_u *DepartmentUpdateOne) SetDepartmentType(v department.DepartmentType) *DepartmentUpdateOne {
	_u.mutation.SetDepartmentType(v)
	return _u
}

// SetNillableDepartmentType sets the "department_type" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableDepartmentType(v *department.DepartmentType) *DepartmentUpdateOne {
	if v != nil {
		_u.SetDepartmentType(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DepartmentUpdateOne) SetIsActive(v bool) *DepartmentUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableIsActive(v *bool) *DepartmentUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetChurchID sets the "church" edge to the Church entity by ID.
func (_u *DepartmentUpdateOne) SetChurchID(id int) *DepartmentUpdateOne {
	_u.mutation.SetChurchID(id)
	return _u
}

// SetChurch sets the "church" edge to the Church entity.
func (_u *DepartmentUpdateOne) SetChurch(v *Church) *DepartmentUpdateOne {
	return _u.SetChurchID(v.ID)
}

// Mutation returns the DepartmentMutation object of the builder.
func (_u *DepartmentUpdateOne) Mutation() *DepartmentMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the Church entity.
func (_u *DepartmentUpdateOne) ClearChurch() *DepartmentUpdateOne {
	_u.mutation.ClearChurch()
	return _u
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (_u *DepartmentUpdateOne) Where(ps ...predicate.Department) *DepartmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepartmentUpdateOne) Select(field string, fields ...string) *DepartmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Department entity.
func (_u *DepartmentUpdateOne) Save(ctx context.Context) (*Department, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentUpdateOne) SaveX(ctx context.Context) *Department {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepartmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepartmentUpdateOne) check() error {
	if v, ok := _u.mutation.DepartmentType(); ok {
		if err := department.DepartmentTypeValidator(v); err != nil {
			return &ValidationError{Name: "department_type", err: fmt.Errorf(`ent: validator failed for field "Department.department_type": %w`, err)}
		}
	}
	if _u.mutation.ChurchCleared() && len(_u.mutation.ChurchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Department.church"`)
	}
	return nil
}

func (_u *DepartmentUpdateOne) sqlSave(ctx context.Context) (_node *Department, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Department.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, department.FieldID)
		for _, f := range fields {
			if !department.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != department.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DepartmentType(); ok {
		_spec.SetField(department.FieldDepartmentType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(department.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ChurchTable,
			Columns: []string{department.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.ChurchTable,
			Columns: []string{department.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Department{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
