// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/group"
	"github.com/ntiGideon/ent/predicate"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GroupUpdate) SetName(v string) *GroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableName(v *string) *GroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupUpdate) SetDescription(v string) *GroupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableDescription(v *string) *GroupUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupUpdate) ClearDescription() *GroupUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupType sets the "group_type" field.
func (_u *GroupUpdate) SetGroupType(v group.GroupType) *GroupUpdate {
	_u.mutation.SetGroupType(v)
	return _u
}

// SetNillableGroupType sets the "group_type" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableGroupType(v *group.GroupType) *GroupUpdate {
	if v != nil {
		_u.SetGroupType(*v)
	}
	return _u
}

// SetMeetingDay sets the "meeting_day" field.
func (_u *GroupUpdate) SetMeetingDay(v group.MeetingDay) *GroupUpdate {
	_u.mutation.SetMeetingDay(v)
	return _u
}

// SetNillableMeetingDay sets the "meeting_day" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableMeetingDay(v *group.MeetingDay) *GroupUpdate {
	if v != nil {
		_u.SetMeetingDay(*v)
	}
	return _u
}

// ClearMeetingDay clears the value of the "meeting_day" field.
func (_u *GroupUpdate) ClearMeetingDay() *GroupUpdate {
	_u.mutation.ClearMeetingDay()
	return _u
}

// SetMeetingTime sets the "meeting_time" field.
func (_u *GroupUpdate) SetMeetingTime(v string) *GroupUpdate {
	_u.mutation.SetMeetingTime(v)
	return _u
}

// SetNillableMeetingTime sets the "meeting_time" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableMeetingTime(v *string) *GroupUpdate {
	if v != nil {
		_u.SetMeetingTime(*v)
	}
	return _u
}

// ClearMeetingTime clears the value of the "meeting_time" field.
func (_u *GroupUpdate) ClearMeetingTime() *GroupUpdate {
	_u.mutation.ClearMeetingTime()
	return _u
}

// SetLocation sets the "location" field.
func (_u *GroupUpdate) SetLocation(v string) *GroupUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableLocation(v *string) *GroupUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *GroupUpdate) ClearLocation() *GroupUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *GroupUpdate) SetIsActive(v bool) *GroupUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableIsActive(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetChurchID sets the "church_id" field.
func (_u *GroupUpdate) SetChurchID(v int) *GroupUpdate {
	_u.mutation.SetChurchID(v)
	return _u
}

// SetNillableChurchID sets the "church_id" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableChurchID(v *int) *GroupUpdate {
	if v != nil {
		_u.SetChurchID(*v)
	}
	return _u
}

// SetLeaderID sets the "leader_id" field.
func (_u *GroupUpdate) SetLeaderID(v int) *GroupUpdate {
	_u.mutation.SetLeaderID(v)
	return _u
}

// SetNillableLeaderID sets the "leader_id" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableLeaderID(v *int) *GroupUpdate {
	if v != nil {
		_u.SetLeaderID(*v)
	}
	return _u
}

// ClearLeaderID clears the value of the "leader_id" field.
func (_u *GroupUpdate) ClearLeaderID() *GroupUpdate {
	_u.mutation.ClearLeaderID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupUpdate) SetCreatedAt(v time.Time) *GroupUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableCreatedAt(v *time.Time) *GroupUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupUpdate) SetUpdatedAt(v time.Time) *GroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChurch sets the "church" edge to the Church entity.
func (_u *GroupUpdate) SetChurch(v *Church) *GroupUpdate {
	return _u.SetChurchID(v.ID)
}

// SetLeader sets the "leader" edge to the Contact entity.
func (_u *GroupUpdate) SetLeader(v *Contact) *GroupUpdate {
	return _u.SetLeaderID(v.ID)
}

// AddMemberIDs adds the "members" edge to the Contact entity by IDs.
func (_u *GroupUpdate) AddMemberIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the Contact entity.
func (_u *GroupUpdate) AddMembers(v ...*Contact) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdate) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the Church entity.
func (_u *GroupUpdate) ClearChurch() *GroupUpdate {
	_u.mutation.ClearChurch()
	return _u
}

// ClearLeader clears the "leader" edge to the Contact entity.
func (_u *GroupUpdate) ClearLeader() *GroupUpdate {
	_u.mutation.ClearLeader()
	return _u
}

// ClearMembers clears all "members" edges to the Contact entity.
func (_u *GroupUpdate) ClearMembers() *GroupUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to Contact entities by IDs.
func (_u *GroupUpdate) RemoveMemberIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to Contact entities.
func (_u *GroupUpdate) RemoveMembers(v ...*Contact) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := group.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdate) check() error {
	if v, ok := _u.mutation.GroupType(); ok {
		if err := group.GroupTypeValidator(v); err != nil {
			return &ValidationError{Name: "group_type", err: fmt.Errorf(`ent: validator failed for field "Group.group_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MeetingDay(); ok {
		if err := group.MeetingDayValidator(v); err != nil {
			return &ValidationError{Name: "meeting_day", err: fmt.Errorf(`ent: validator failed for field "Group.meeting_day": %w`, err)}
		}
	}
	if _u.mutation.ChurchCleared() && len(_u.mutation.ChurchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.church"`)
	}
	return nil
}

func (_u *GroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GroupType(); ok {
		_spec.SetField(group.FieldGroupType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MeetingDay(); ok {
		_spec.SetField(group.FieldMeetingDay, field.TypeEnum, value)
	}
	if _u.mutation.MeetingDayCleared() {
		_spec.ClearField(group.FieldMeetingDay, field.TypeEnum)
	}
	if value, ok := _u.mutation.MeetingTime(); ok {
		_spec.SetField(group.FieldMeetingTime, field.TypeString, value)
	}
	if _u.mutation.MeetingTimeCleared() {
		_spec.ClearField(group.FieldMeetingTime, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(group.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(group.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(group.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(group.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.ChurchTable,
			Columns: []string{group.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.ChurchTable,
			Columns: []string{group.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   group.LeaderTable,
			Columns: []string{group.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   group.LeaderTable,
			Columns: []string{group.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: group.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: group.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: group.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMutation
}

// SetName sets the "name" field.
func (_u *GroupUpdateOne) SetName(v string) *GroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableName(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupUpdateOne) SetDescription(v string) *GroupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableDescription(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupUpdateOne) ClearDescription() *GroupUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupType sets the "group_type" field.
func (_u *GroupUpdateOne) SetGroupType(v group.GroupType) *GroupUpdateOne {
	_u.mutation.SetGroupType(v)
	return _u
}

// SetNillableGroupType sets the "group_type" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableGroupType(v *group.GroupType) *GroupUpdateOne {
	if v != nil {
		_u.SetGroupType(*v)
	}
	return _u
}

// SetMeetingDay sets the "meeting_day" field.
func (_u *GroupUpdateOne) SetMeetingDay(v group.MeetingDay) *GroupUpdateOne {
	_u.mutation.SetMeetingDay(v)
	return _u
}

// SetNillableMeetingDay sets the "meeting_day" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableMeetingDay(v *group.MeetingDay) *GroupUpdateOne {
	if v != nil {
		_u.SetMeetingDay(*v)
	}
	return _u
}

// ClearMeetingDay clears the value of the "meeting_day" field.
func (_u *GroupUpdateOne) ClearMeetingDay() *GroupUpdateOne {
	_u.mutation.ClearMeetingDay()
	return _u
}

// SetMeetingTime sets the "meeting_time" field.
func (_u *GroupUpdateOne) SetMeetingTime(v string) *GroupUpdateOne {
	_u.mutation.SetMeetingTime(v)
	return _u
}

// SetNillableMeetingTime sets the "meeting_time" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableMeetingTime(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetMeetingTime(*v)
	}
	return _u
}

// ClearMeetingTime clears the value of the "meeting_time" field.
func (_u *GroupUpdateOne) ClearMeetingTime() *GroupUpdateOne {
	_u.mutation.ClearMeetingTime()
	return _u
}

// SetLocation sets the "location" field.
func (_u *GroupUpdateOne) SetLocation(v string) *GroupUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableLocation(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *GroupUpdateOne) ClearLocation() *GroupUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *GroupUpdateOne) SetIsActive(v bool) *GroupUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableIsActive(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetChurchID sets the "church_id" field.
func (_u *GroupUpdateOne) SetChurchID(v int) *GroupUpdateOne {
	_u.mutation.SetChurchID(v)
	return _u
}

// SetNillableChurchID sets the "church_id" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableChurchID(v *int) *GroupUpdateOne {
	if v != nil {
		_u.SetChurchID(*v)
	}
	return _u
}

// SetLeaderID sets the "leader_id" field.
func (_u *GroupUpdateOne) SetLeaderID(v int) *GroupUpdateOne {
	_u.mutation.SetLeaderID(v)
	return _u
}

// SetNillableLeaderID sets the "leader_id" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableLeaderID(v *int) *GroupUpdateOne {
	if v != nil {
		_u.SetLeaderID(*v)
	}
	return _u
}

// ClearLeaderID clears the value of the "leader_id" field.
func (_u *GroupUpdateOne) ClearLeaderID() *GroupUpdateOne {
	_u.mutation.ClearLeaderID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupUpdateOne) SetCreatedAt(v time.Time) *GroupUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableCreatedAt(v *time.Time) *GroupUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupUpdateOne) SetUpdatedAt(v time.Time) *GroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChurch sets the "church" edge to the Church entity.
func (_u *GroupUpdateOne) SetChurch(v *Church) *GroupUpdateOne {
	return _u.SetChurchID(v.ID)
}

// SetLeader sets the "leader" edge to the Contact entity.
func (_u *GroupUpdateOne) SetLeader(v *Contact) *GroupUpdateOne {
	return _u.SetLeaderID(v.ID)
}

// AddMemberIDs adds the "members" edge to the Contact entity by IDs.
func (_u *GroupUpdateOne) AddMemberIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the Contact entity.
func (_u *GroupUpdateOne) AddMembers(v ...*Contact) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdateOne) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the Church entity.
func (_u *GroupUpdateOne) ClearChurch() *GroupUpdateOne {
	_u.mutation.ClearChurch()
	return _u
}

// ClearLeader clears the "leader" edge to the Contact entity.
func (_u *GroupUpdateOne) ClearLeader() *GroupUpdateOne {
	_u.mutation.ClearLeader()
	return _u
}

// ClearMembers clears all "members" edges to the Contact entity.
func (_u *GroupUpdateOne) ClearMembers() *GroupUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to Contact entities by IDs.
func (_u *GroupUpdateOne) RemoveMemberIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to Contact entities.
func (_u *GroupUpdateOne) RemoveMembers(v ...*Contact) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdateOne) Where(ps ...predicate.Group) *GroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Group entity.
func (_u *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := group.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdateOne) check() error {
	if v, ok := _u.mutation.GroupType(); ok {
		if err := group.GroupTypeValidator(v); err != nil {
			return &ValidationError{Name: "group_type", err: fmt.Errorf(`ent: validator failed for field "Group.group_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MeetingDay(); ok {
		if err := group.MeetingDayValidator(v); err != nil {
			return &ValidationError{Name: "meeting_day", err: fmt.Errorf(`ent: validator failed for field "Group.meeting_day": %w`, err)}
		}
	}
	if _u.mutation.ChurchCleared() && len(_u.mutation.ChurchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.church"`)
	}
	return nil
}

func (_u *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, group.FieldID)
		for _, f := range fields {
			if !group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GroupType(); ok {
		_spec.SetField(group.FieldGroupType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MeetingDay(); ok {
		_spec.SetField(group.FieldMeetingDay, field.TypeEnum, value)
	}
	if _u.mutation.MeetingDayCleared() {
		_spec.ClearField(group.FieldMeetingDay, field.TypeEnum)
	}
	if value, ok := _u.mutation.MeetingTime(); ok {
		_spec.SetField(group.FieldMeetingTime, field.TypeString, value)
	}
	if _u.mutation.MeetingTimeCleared() {
		_spec.ClearField(group.FieldMeetingTime, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(group.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(group.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(group.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(group.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.ChurchTable,
			Columns: []string{group.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.ChurchTable,
			Columns: []string{group.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   group.LeaderTable,
			Columns: []string{group.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   group.LeaderTable,
			Columns: []string{group.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: group.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: group.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: group.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Group{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
