// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/pastoralnote"
	"github.com/ntiGideon/ent/user"
)

// PastoralNoteCreate is the builder for creating a PastoralNote entity.
type PastoralNoteCreate struct {
	config
	mutation *PastoralNoteMutation
	hooks    []Hook
}

// SetVisitDate sets the "visit_date" field.
func (_c *PastoralNoteCreate) SetVisitDate(v time.Time) *PastoralNoteCreate {
	_c.mutation.SetVisitDate(v)
	return _c
}

// SetCareType sets the "care_type" field.
func (_c *PastoralNoteCreate) SetCareType(v pastoralnote.CareType) *PastoralNoteCreate {
	_c.mutation.SetCareType(v)
	return _c
}

// SetNillableCareType sets the "care_type" field if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableCareType(v *pastoralnote.CareType) *PastoralNoteCreate {
	if v != nil {
		_c.SetCareType(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PastoralNoteCreate) SetNotes(v string) *PastoralNoteCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNeedsFollowUp sets the "needs_follow_up" field.
func (_c *PastoralNoteCreate) SetNeedsFollowUp(v bool) *PastoralNoteCreate {
	_c.mutation.SetNeedsFollowUp(v)
	return _c
}

// SetNillableNeedsFollowUp sets the "needs_follow_up" field if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableNeedsFollowUp(v *bool) *PastoralNoteCreate {
	if v != nil {
		_c.SetNeedsFollowUp(*v)
	}
	return _c
}

// SetFollowUpDate sets the "follow_up_date" field.
func (_c *PastoralNoteCreate) SetFollowUpDate(v time.Time) *PastoralNoteCreate {
	_c.mutation.SetFollowUpDate(v)
	return _c
}

// SetNillableFollowUpDate sets the "follow_up_date" field if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableFollowUpDate(v *time.Time) *PastoralNoteCreate {
	if v != nil {
		_c.SetFollowUpDate(*v)
	}
	return _c
}

// SetFollowUpDone sets the "follow_up_done" field.
func (_c *PastoralNoteCreate) SetFollowUpDone(v bool) *PastoralNoteCreate {
	_c.mutation.SetFollowUpDone(v)
	return _c
}

// SetNillableFollowUpDone sets the "follow_up_done" field if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableFollowUpDone(v *bool) *PastoralNoteCreate {
	if v != nil {
		_c.SetFollowUpDone(*v)
	}
	return _c
}

// SetContactID sets the "contact_id" field.
func (_c *PastoralNoteCreate) SetContactID(v int) *PastoralNoteCreate {
	_c.mutation.SetContactID(v)
	return _c
}

// SetChurchID sets the "church_id" field.
func (_c *PastoralNoteCreate) SetChurchID(v int) *PastoralNoteCreate {
	_c.mutation.SetChurchID(v)
	return _c
}

// SetRecordedByID sets the "recorded_by_id" field.
func (_c *PastoralNoteCreate) SetRecordedByID(v int) *PastoralNoteCreate {
	_c.mutation.SetRecordedByID(v)
	return _c
}

// SetNillableRecordedByID sets the "recorded_by_id" field if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableRecordedByID(v *int) *PastoralNoteCreate {
	if v != nil {
		_c.SetRecordedByID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PastoralNoteCreate) SetCreatedAt(v time.Time) *PastoralNoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableCreatedAt(v *time.Time) *PastoralNoteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PastoralNoteCreate) SetUpdatedAt(v time.Time) *PastoralNoteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableUpdatedAt(v *time.Time) *PastoralNoteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChurch sets the "church" edge to the Church entity.
func (_c *PastoralNoteCreate) SetChurch(v *Church) *PastoralNoteCreate {
	return _c.SetChurchID(v.ID)
}

// SetMemberID sets the "member" edge to the Contact entity by ID.
func (_c *PastoralNoteCreate) SetMemberID(id int) *PastoralNoteCreate {
	_c.mutation.SetMemberID(id)
	return _c
}

// SetMember sets the "member" edge to the Contact entity.
func (_c *PastoralNoteCreate) SetMember(v *Contact) *PastoralNoteCreate {
	return _c.SetMemberID(v.ID)
}

// SetRecorderID sets the "recorder" edge to the User entity by ID.
func (_c *PastoralNoteCreate) SetRecorderID(id int) *PastoralNoteCreate {
	_c.mutation.SetRecorderID(id)
	return _c
}

// SetNillableRecorderID sets the "recorder" edge to the User entity by ID if the given value is not nil.
func (_c *PastoralNoteCreate) SetNillableRecorderID(id *int) *PastoralNoteCreate {
	if id != nil {
		_c = _c.SetRecorderID(*id)
	}
	return _c
}

// SetRecorder sets the "recorder" edge to the User entity.
func (_c *PastoralNoteCreate) SetRecorder(v *User) *PastoralNoteCreate {
	return _c.SetRecorderID(v.ID)
}

// Mutation returns the PastoralNoteMutation object of the builder.
func (_c *PastoralNoteCreate) Mutation() *PastoralNoteMutation {
	return _c.mutation
}

// Save creates the PastoralNote in the database.
func (_c *PastoralNoteCreate) Save(ctx context.Context) (*PastoralNote, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PastoralNoteCreate) SaveX(ctx context.Context) *PastoralNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PastoralNoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PastoralNoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PastoralNoteCreate) defaults() {
	if _, ok := _c.mutation.CareType(); !ok {
		v := pastoralnote.DefaultCareType
		_c.mutation.SetCareType(v)
	}
	if _, ok := _c.mutation.NeedsFollowUp(); !ok {
		v := pastoralnote.DefaultNeedsFollowUp
		_c.mutation.SetNeedsFollowUp(v)
	}
	if _, ok := _c.mutation.FollowUpDone(); !ok {
		v := pastoralnote.DefaultFollowUpDone
		_c.mutation.SetFollowUpDone(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pastoralnote.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pastoralnote.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PastoralNoteCreate) check() error {
	if _, ok := _c.mutation.VisitDate(); !ok {
		return &ValidationError{Name: "visit_date", err: errors.New(`ent: missing required field "PastoralNote.visit_date"`)}
	}
	if _, ok := _c.mutation.CareType(); !ok {
		return &ValidationError{Name: "care_type", err: errors.New(`ent: missing required field "PastoralNote.care_type"`)}
	}
	if v, ok := _c.mutation.CareType(); ok {
		if err := pastoralnote.CareTypeValidator(v); err != nil {
			return &ValidationError{Name: "care_type", err: fmt.Errorf(`ent: validator failed for field "PastoralNote.care_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "PastoralNote.notes"`)}
	}
	if _, ok := _c.mutation.NeedsFollowUp(); !ok {
		return &ValidationError{Name: "needs_follow_up", err: errors.New(`ent: missing required field "PastoralNote.needs_follow_up"`)}
	}
	if _, ok := _c.mutation.FollowUpDone(); !ok {
		return &ValidationError{Name: "follow_up_done", err: errors.New(`ent: missing required field "PastoralNote.follow_up_done"`)}
	}
	if _, ok := _c.mutation.ContactID(); !ok {
		return &ValidationError{Name: "contact_id", err: errors.New(`ent: missing required field "PastoralNote.contact_id"`)}
	}
	if _, ok := _c.mutation.ChurchID(); !ok {
		return &ValidationError{Name: "church_id", err: errors.New(`ent: missing required field "PastoralNote.church_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PastoralNote.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PastoralNote.updated_at"`)}
	}
	if len(_c.mutation.ChurchIDs()) == 0 {
		return &ValidationError{Name: "church", err: errors.New(`ent: missing required edge "PastoralNote.church"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "PastoralNote.member"`)}
	}
	return nil
}

func (_c *PastoralNoteCreate) sqlSave(ctx context.Context) (*PastoralNote, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PastoralNoteCreate) createSpec() (*PastoralNote, *sqlgraph.CreateSpec) {
	var (
		_node = &PastoralNote{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pastoralnote.Table, sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.VisitDate(); ok {
		_spec.SetField(pastoralnote.FieldVisitDate, field.TypeTime, value)
		_node.VisitDate = value
	}
	if value, ok := _c.mutation.CareType(); ok {
		_spec.SetField(pastoralnote.FieldCareType, field.TypeEnum, value)
		_node.CareType = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(pastoralnote.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.NeedsFollowUp(); ok {
		_spec.SetField(pastoralnote.FieldNeedsFollowUp, field.TypeBool, value)
		_node.NeedsFollowUp = value
	}
	if value, ok := _c.mutation.FollowUpDate(); ok {
		_spec.SetField(pastoralnote.FieldFollowUpDate, field.TypeTime, value)
		_node.FollowUpDate = value
	}
	if value, ok := _c.mutation.FollowUpDone(); ok {
		_spec.SetField(pastoralnote.FieldFollowUpDone, field.TypeBool, value)
		_node.FollowUpDone = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pastoralnote.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pastoralnote.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pastoralnote.ChurchTable,
			Columns: []string{pastoralnote.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChurchID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pastoralnote.MemberTable,
			Columns: []string{pastoralnote.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContactID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecorderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pastoralnote.RecorderTable,
			Columns: []string{pastoralnote.RecorderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecordedByID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PastoralNoteCreateBulk is the builder for creating many PastoralNote entities in bulk.
type PastoralNoteCreateBulk struct {
	config
	err      error
	builders []*PastoralNoteCreate
}

// Save creates the PastoralNote entities in the database.
func (_c *PastoralNoteCreateBulk) Save(ctx context.Context) ([]*PastoralNote, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PastoralNote, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PastoralNoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PastoralNoteCreateBulk) SaveX(ctx context.Context) []*PastoralNote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PastoralNoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PastoralNoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
