// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/pastoralnote"
	"github.com/ntiGideon/ent/predicate"
	"github.com/ntiGideon/ent/user"
)

// PastoralNoteQuery is the builder for querying PastoralNote entities.
type PastoralNoteQuery struct {
	config
	ctx          *QueryContext
	order        []pastoralnote.OrderOption
	inters       []Interceptor
	predicates   []predicate.PastoralNote
	withChurch   *ChurchQuery
	withMember   *ContactQuery
	withRecorder *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PastoralNoteQuery builder.
func (_q *PastoralNoteQuery) Where(ps ...predicate.PastoralNote) *PastoralNoteQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PastoralNoteQuery) Limit(limit int) *PastoralNoteQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PastoralNoteQuery) Offset(offset int) *PastoralNoteQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PastoralNoteQuery) Unique(unique bool) *PastoralNoteQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PastoralNoteQuery) Order(o ...pastoralnote.OrderOption) *PastoralNoteQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChurch chains the current query on the "church" edge.
func (_q *PastoralNoteQuery) QueryChurch() *ChurchQuery {
	query := (&ChurchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pastoralnote.Table, pastoralnote.FieldID, selector),
			sqlgraph.To(church.Table, church.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pastoralnote.ChurchTable, pastoralnote.ChurchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMember chains the current query on the "member" edge.
func (_q *PastoralNoteQuery) QueryMember() *ContactQuery {
	query := (&ContactClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pastoralnote.Table, pastoralnote.FieldID, selector),
			sqlgraph.To(contact.Table, contact.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pastoralnote.MemberTable, pastoralnote.MemberColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRecorder chains the current query on the "recorder" edge.
func (_q *PastoralNoteQuery) QueryRecorder() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pastoralnote.Table, pastoralnote.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pastoralnote.RecorderTable, pastoralnote.RecorderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PastoralNote entity from the query.
// Returns a *NotFoundError when no PastoralNote was found.
func (_q *PastoralNoteQuery) First(ctx context.Context) (*PastoralNote, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pastoralnote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PastoralNoteQuery) FirstX(ctx context.Context) *PastoralNote {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PastoralNote ID from the query.
// Returns a *NotFoundError when no PastoralNote ID was found.
func (_q *PastoralNoteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pastoralnote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PastoralNoteQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PastoralNote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PastoralNote entity is found.
// Returns a *NotFoundError when no PastoralNote entities are found.
func (_q *PastoralNoteQuery) Only(ctx context.Context) (*PastoralNote, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pastoralnote.Label}
	default:
		return nil, &NotSingularError{pastoralnote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PastoralNoteQuery) OnlyX(ctx context.Context) *PastoralNote {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PastoralNote ID in the query.
// Returns a *NotSingularError when more than one PastoralNote ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PastoralNoteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pastoralnote.Label}
	default:
		err = &NotSingularError{pastoralnote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PastoralNoteQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PastoralNotes.
func (_q *PastoralNoteQuery) All(ctx context.Context) ([]*PastoralNote, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PastoralNote, *PastoralNoteQuery]()
	return withInterceptors[[]*PastoralNote](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PastoralNoteQuery) AllX(ctx context.Context) []*PastoralNote {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PastoralNote IDs.
func (_q *PastoralNoteQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pastoralnote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PastoralNoteQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PastoralNoteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PastoralNoteQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PastoralNoteQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PastoralNoteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PastoralNoteQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PastoralNoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PastoralNoteQuery) Clone() *PastoralNoteQuery {
	if _q == nil {
		return nil
	}
	return &PastoralNoteQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]pastoralnote.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.PastoralNote{}, _q.predicates...),
		withChurch:   _q.withChurch.Clone(),
		withMember:   _q.withMember.Clone(),
		withRecorder: _q.withRecorder.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChurch tells the query-builder to eager-load the nodes that are connected to
// the "church" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PastoralNoteQuery) WithChurch(opts ...func(*ChurchQuery)) *PastoralNoteQuery {
	query := (&ChurchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChurch = query
	return _q
}

// WithMember tells the query-builder to eager-load the nodes that are connected to
// the "member" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PastoralNoteQuery) WithMember(opts ...func(*ContactQuery)) *PastoralNoteQuery {
	query := (&ContactClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMember = query
	return _q
}

// WithRecorder tells the query-builder to eager-load the nodes that are connected to
// the "recorder" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PastoralNoteQuery) WithRecorder(opts ...func(*UserQuery)) *PastoralNoteQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRecorder = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VisitDate time.Time `json:"visit_date,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PastoralNote.Query().
//		GroupBy(pastoralnote.FieldVisitDate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PastoralNoteQuery) GroupBy(field string, fields ...string) *PastoralNoteGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PastoralNoteGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pastoralnote.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VisitDate time.Time `json:"visit_date,omitempty"`
//	}
//
//	client.PastoralNote.Query().
//		Select(pastoralnote.FieldVisitDate).
//		Scan(ctx, &v)
func (_q *PastoralNoteQuery) Select(fields ...string) *PastoralNoteSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PastoralNoteSelect{PastoralNoteQuery: _q}
	sbuild.label = pastoralnote.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PastoralNoteSelect configured with the given aggregations.
func (_q *PastoralNoteQuery) Aggregate(fns ...AggregateFunc) *PastoralNoteSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PastoralNoteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pastoralnote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PastoralNoteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PastoralNote, error) {
	var (
		nodes       = []*PastoralNote{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withChurch != nil,
			_q.withMember != nil,
			_q.withRecorder != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PastoralNote).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PastoralNote{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChurch; query != nil {
		if err := _q.loadChurch(ctx, query, nodes, nil,
			func(n *PastoralNote, e *Church) { n.Edges.Church = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMember; query != nil {
		if err := _q.loadMember(ctx, query, nodes, nil,
			func(n *PastoralNote, e *Contact) { n.Edges.Member = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRecorder; query != nil {
		if err := _q.loadRecorder(ctx, query, nodes, nil,
			func(n *PastoralNote, e *User) { n.Edges.Recorder = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PastoralNoteQuery) loadChurch(ctx context.Context, query *ChurchQuery, nodes []*PastoralNote, init func(*PastoralNote), assign func(*PastoralNote, *Church)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PastoralNote)
	for i := range nodes {
		fk := nodes[i].ChurchID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(church.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "church_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PastoralNoteQuery) loadMember(ctx context.Context, query *ContactQuery, nodes []*PastoralNote, init func(*PastoralNote), assign func(*PastoralNote, *Contact)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PastoralNote)
	for i := range nodes {
		fk := nodes[i].ContactID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contact.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "contact_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PastoralNoteQuery) loadRecorder(ctx context.Context, query *UserQuery, nodes []*PastoralNote, init func(*PastoralNote), assign func(*PastoralNote, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PastoralNote)
	for i := range nodes {
		fk := nodes[i].RecordedByID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "recorded_by_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PastoralNoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PastoralNoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pastoralnote.Table, pastoralnote.Columns, sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pastoralnote.FieldID)
		for i := range fields {
			if fields[i] != pastoralnote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChurch != nil {
			_spec.Node.AddColumnOnce(pastoralnote.FieldChurchID)
		}
		if _q.withMember != nil {
			_spec.Node.AddColumnOnce(pastoralnote.FieldContactID)
		}
		if _q.withRecorder != nil {
			_spec.Node.AddColumnOnce(pastoralnote.FieldRecordedByID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PastoralNoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pastoralnote.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pastoralnote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PastoralNoteGroupBy is the group-by builder for PastoralNote entities.
type PastoralNoteGroupBy struct {
	selector
	build *PastoralNoteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PastoralNoteGroupBy) Aggregate(fns ...AggregateFunc) *PastoralNoteGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PastoralNoteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PastoralNoteQuery, *PastoralNoteGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PastoralNoteGroupBy) sqlScan(ctx context.Context, root *PastoralNoteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PastoralNoteSelect is the builder for selecting fields of PastoralNote entities.
type PastoralNoteSelect struct {
	*PastoralNoteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PastoralNoteSelect) Aggregate(fns ...AggregateFunc) *PastoralNoteSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PastoralNoteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PastoralNoteQuery, *PastoralNoteSelect](ctx, _s.PastoralNoteQuery, _s, _s.inters, v)
}

func (_s *PastoralNoteSelect) sqlScan(ctx context.Context, root *PastoralNoteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
