// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/pledge"
)

// PledgeCreate is the builder for creating a Pledge entity.
type PledgeCreate struct {
	config
	mutation *PledgeMutation
	hooks    []Hook
}

// SetContactID sets the "contact_id" field.
func (_c *PledgeCreate) SetContactID(v int) *PledgeCreate {
	_c.mutation.SetContactID(v)
	return _c
}

// SetChurchID sets the "church_id" field.
func (_c *PledgeCreate) SetChurchID(v int) *PledgeCreate {
	_c.mutation.SetChurchID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PledgeCreate) SetTitle(v string) *PledgeCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *PledgeCreate) SetCategory(v string) *PledgeCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *PledgeCreate) SetNillableCategory(v *string) *PledgeCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PledgeCreate) SetAmount(v float64) *PledgeCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PledgeCreate) SetCurrency(v string) *PledgeCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PledgeCreate) SetNillableCurrency(v *string) *PledgeCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *PledgeCreate) SetStartDate(v time.Time) *PledgeCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *PledgeCreate) SetEndDate(v time.Time) *PledgeCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *PledgeCreate) SetNillableEndDate(v *time.Time) *PledgeCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *PledgeCreate) SetFrequency(v pledge.Frequency) *PledgeCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_c *PledgeCreate) SetNillableFrequency(v *pledge.Frequency) *PledgeCreate {
	if v != nil {
		_c.SetFrequency(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PledgeCreate) SetNotes(v string) *PledgeCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PledgeCreate) SetNillableNotes(v *string) *PledgeCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PledgeCreate) SetCreatedAt(v time.Time) *PledgeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PledgeCreate) SetNillableCreatedAt(v *time.Time) *PledgeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetContact sets the "contact" edge to the Contact entity.
func (_c *PledgeCreate) SetContact(v *Contact) *PledgeCreate {
	return _c.SetContactID(v.ID)
}

// SetChurch sets the "church" edge to the Church entity.
func (_c *PledgeCreate) SetChurch(v *Church) *PledgeCreate {
	return _c.SetChurchID(v.ID)
}

// Mutation returns the PledgeMutation object of the builder.
func (_c *PledgeCreate) Mutation() *PledgeMutation {
	return _c.mutation
}

// Save creates the Pledge in the database.
func (_c *PledgeCreate) Save(ctx context.Context) (*Pledge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PledgeCreate) SaveX(ctx context.Context) *Pledge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PledgeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PledgeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PledgeCreate) defaults() {
	if _, ok := _c.mutation.Category(); !ok {
		v := pledge.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := pledge.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		v := pledge.DefaultFrequency
		_c.mutation.SetFrequency(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pledge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PledgeCreate) check() error {
	if _, ok := _c.mutation.ContactID(); !ok {
		return &ValidationError{Name: "contact_id", err: errors.New(`ent: missing required field "Pledge.contact_id"`)}
	}
	if _, ok := _c.mutation.ChurchID(); !ok {
		return &ValidationError{Name: "church_id", err: errors.New(`ent: missing required field "Pledge.church_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Pledge.title"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Pledge.category"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Pledge.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Pledge.currency"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Pledge.start_date"`)}
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		return &ValidationError{Name: "frequency", err: errors.New(`ent: missing required field "Pledge.frequency"`)}
	}
	if v, ok := _c.mutation.Frequency(); ok {
		if err := pledge.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "Pledge.frequency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Pledge.created_at"`)}
	}
	if len(_c.mutation.ContactIDs()) == 0 {
		return &ValidationError{Name: "contact", err: errors.New(`ent: missing required edge "Pledge.contact"`)}
	}
	if len(_c.mutation.ChurchIDs()) == 0 {
		return &ValidationError{Name: "church", err: errors.New(`ent: missing required edge "Pledge.church"`)}
	}
	return nil
}

func (_c *PledgeCreate) sqlSave(ctx context.Context) (*Pledge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PledgeCreate) createSpec() (*Pledge, *sqlgraph.CreateSpec) {
	var (
		_node = &Pledge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pledge.Table, sqlgraph.NewFieldSpec(pledge.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(pledge.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(pledge.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(pledge.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(pledge.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(pledge.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(pledge.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(pledge.FieldFrequency, field.TypeEnum, value)
		_node.Frequency = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(pledge.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pledge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ContactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pledge.ContactTable,
			Columns: []string{pledge.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContactID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pledge.ChurchTable,
			Columns: []string{pledge.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChurchID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PledgeCreateBulk is the builder for creating many Pledge entities in bulk.
type PledgeCreateBulk struct {
	config
	err      error
	builders []*PledgeCreate
}

// Save creates the Pledge entities in the database.
func (_c *PledgeCreateBulk) Save(ctx context.Context) ([]*Pledge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pledge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PledgeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PledgeCreateBulk) SaveX(ctx context.Context) []*Pledge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PledgeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PledgeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
