// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/pledge"
	"github.com/ntiGideon/ent/predicate"
)

// PledgeQuery is the builder for querying Pledge entities.
type PledgeQuery struct {
	config
	ctx         *QueryContext
	order       []pledge.OrderOption
	inters      []Interceptor
	predicates  []predicate.Pledge
	withContact *ContactQuery
	withChurch  *ChurchQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PledgeQuery builder.
func (_q *PledgeQuery) Where(ps ...predicate.Pledge) *PledgeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PledgeQuery) Limit(limit int) *PledgeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PledgeQuery) Offset(offset int) *PledgeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PledgeQuery) Unique(unique bool) *PledgeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PledgeQuery) Order(o ...pledge.OrderOption) *PledgeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryContact chains the current query on the "contact" edge.
func (_q *PledgeQuery) QueryContact() *ContactQuery {
	query := (&ContactClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pledge.Table, pledge.FieldID, selector),
			sqlgraph.To(contact.Table, contact.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pledge.ContactTable, pledge.ContactColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChurch chains the current query on the "church" edge.
func (_q *PledgeQuery) QueryChurch() *ChurchQuery {
	query := (&ChurchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pledge.Table, pledge.FieldID, selector),
			sqlgraph.To(church.Table, church.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pledge.ChurchTable, pledge.ChurchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Pledge entity from the query.
// Returns a *NotFoundError when no Pledge was found.
func (_q *PledgeQuery) First(ctx context.Context) (*Pledge, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pledge.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PledgeQuery) FirstX(ctx context.Context) *Pledge {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Pledge ID from the query.
// Returns a *NotFoundError when no Pledge ID was found.
func (_q *PledgeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pledge.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PledgeQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Pledge entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Pledge entity is found.
// Returns a *NotFoundError when no Pledge entities are found.
func (_q *PledgeQuery) Only(ctx context.Context) (*Pledge, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pledge.Label}
	default:
		return nil, &NotSingularError{pledge.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PledgeQuery) OnlyX(ctx context.Context) *Pledge {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Pledge ID in the query.
// Returns a *NotSingularError when more than one Pledge ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PledgeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pledge.Label}
	default:
		err = &NotSingularError{pledge.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PledgeQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Pledges.
func (_q *PledgeQuery) All(ctx context.Context) ([]*Pledge, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Pledge, *PledgeQuery]()
	return withInterceptors[[]*Pledge](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PledgeQuery) AllX(ctx context.Context) []*Pledge {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Pledge IDs.
func (_q *PledgeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pledge.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PledgeQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PledgeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PledgeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PledgeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PledgeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PledgeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PledgeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PledgeQuery) Clone() *PledgeQuery {
	if _q == nil {
		return nil
	}
	return &PledgeQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]pledge.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.Pledge{}, _q.predicates...),
		withContact: _q.withContact.Clone(),
		withChurch:  _q.withChurch.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithContact tells the query-builder to eager-load the nodes that are connected to
// the "contact" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PledgeQuery) WithContact(opts ...func(*ContactQuery)) *PledgeQuery {
	query := (&ContactClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContact = query
	return _q
}

// WithChurch tells the query-builder to eager-load the nodes that are connected to
// the "church" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PledgeQuery) WithChurch(opts ...func(*ChurchQuery)) *PledgeQuery {
	query := (&ChurchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChurch = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ContactID int `json:"contact_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Pledge.Query().
//		GroupBy(pledge.FieldContactID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PledgeQuery) GroupBy(field string, fields ...string) *PledgeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PledgeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pledge.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ContactID int `json:"contact_id,omitempty"`
//	}
//
//	client.Pledge.Query().
//		Select(pledge.FieldContactID).
//		Scan(ctx, &v)
func (_q *PledgeQuery) Select(fields ...string) *PledgeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PledgeSelect{PledgeQuery: _q}
	sbuild.label = pledge.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PledgeSelect configured with the given aggregations.
func (_q *PledgeQuery) Aggregate(fns ...AggregateFunc) *PledgeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PledgeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pledge.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PledgeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Pledge, error) {
	var (
		nodes       = []*Pledge{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withContact != nil,
			_q.withChurch != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Pledge).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Pledge{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withContact; query != nil {
		if err := _q.loadContact(ctx, query, nodes, nil,
			func(n *Pledge, e *Contact) { n.Edges.Contact = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChurch; query != nil {
		if err := _q.loadChurch(ctx, query, nodes, nil,
			func(n *Pledge, e *Church) { n.Edges.Church = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PledgeQuery) loadContact(ctx context.Context, query *ContactQuery, nodes []*Pledge, init func(*Pledge), assign func(*Pledge, *Contact)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Pledge)
	for i := range nodes {
		fk := nodes[i].ContactID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contact.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "contact_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PledgeQuery) loadChurch(ctx context.Context, query *ChurchQuery, nodes []*Pledge, init func(*Pledge), assign func(*Pledge, *Church)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Pledge)
	for i := range nodes {
		fk := nodes[i].ChurchID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(church.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "church_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PledgeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PledgeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pledge.Table, pledge.Columns, sqlgraph.NewFieldSpec(pledge.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pledge.FieldID)
		for i := range fields {
			if fields[i] != pledge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withContact != nil {
			_spec.Node.AddColumnOnce(pledge.FieldContactID)
		}
		if _q.withChurch != nil {
			_spec.Node.AddColumnOnce(pledge.FieldChurchID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PledgeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pledge.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pledge.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PledgeGroupBy is the group-by builder for Pledge entities.
type PledgeGroupBy struct {
	selector
	build *PledgeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PledgeGroupBy) Aggregate(fns ...AggregateFunc) *PledgeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PledgeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PledgeQuery, *PledgeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PledgeGroupBy) sqlScan(ctx context.Context, root *PledgeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PledgeSelect is the builder for selecting fields of Pledge entities.
type PledgeSelect struct {
	*PledgeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PledgeSelect) Aggregate(fns ...AggregateFunc) *PledgeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PledgeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PledgeQuery, *PledgeSelect](ctx, _s.PledgeQuery, _s, _s.inters, v)
}

func (_s *PledgeSelect) sqlScan(ctx context.Context, root *PledgeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
