// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ntiGideon/ent/announcement"
	"github.com/ntiGideon/ent/attendance"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/communication"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/department"
	"github.com/ntiGideon/ent/document"
	"github.com/ntiGideon/ent/event"
	"github.com/ntiGideon/ent/finance"
	"github.com/ntiGideon/ent/group"
	"github.com/ntiGideon/ent/invitation"
	"github.com/ntiGideon/ent/milestone"
	"github.com/ntiGideon/ent/pastoralnote"
	"github.com/ntiGideon/ent/pledge"
	"github.com/ntiGideon/ent/prayerrequest"
	"github.com/ntiGideon/ent/programentry"
	"github.com/ntiGideon/ent/relationship"
	"github.com/ntiGideon/ent/roster"
	"github.com/ntiGideon/ent/schema"
	"github.com/ntiGideon/ent/sermon"
	"github.com/ntiGideon/ent/session"
	"github.com/ntiGideon/ent/user"
	"github.com/ntiGideon/ent/visitor"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	announcementFields := schema.Announcement{}.Fields()
	_ = announcementFields
	// announcementDescIsPublished is the schema descriptor for is_published field.
	announcementDescIsPublished := announcementFields[3].Descriptor()
	// announcement.DefaultIsPublished holds the default value on creation for the is_published field.
	announcement.DefaultIsPublished = announcementDescIsPublished.Default.(bool)
	// announcementDescCreatedAt is the schema descriptor for created_at field.
	announcementDescCreatedAt := announcementFields[5].Descriptor()
	// announcement.DefaultCreatedAt holds the default value on creation for the created_at field.
	announcement.DefaultCreatedAt = announcementDescCreatedAt.Default.(func() time.Time)
	// announcementDescUpdatedAt is the schema descriptor for updated_at field.
	announcementDescUpdatedAt := announcementFields[6].Descriptor()
	// announcement.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	announcement.DefaultUpdatedAt = announcementDescUpdatedAt.Default.(func() time.Time)
	// announcement.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	announcement.UpdateDefaultUpdatedAt = announcementDescUpdatedAt.UpdateDefault.(func() time.Time)
	attendanceFields := schema.Attendance{}.Fields()
	_ = attendanceFields
	// attendanceDescCheckInTime is the schema descriptor for check_in_time field.
	attendanceDescCheckInTime := attendanceFields[4].Descriptor()
	// attendance.DefaultCheckInTime holds the default value on creation for the check_in_time field.
	attendance.DefaultCheckInTime = attendanceDescCheckInTime.Default.(func() time.Time)
	churchFields := schema.Church{}.Fields()
	_ = churchFields
	// churchDescCity is the schema descriptor for city field.
	churchDescCity := churchFields[2].Descriptor()
	// church.DefaultCity holds the default value on creation for the city field.
	church.DefaultCity = churchDescCity.Default.(string)
	// churchDescCountry is the schema descriptor for country field.
	churchDescCountry := churchFields[5].Descriptor()
	// church.DefaultCountry holds the default value on creation for the country field.
	church.DefaultCountry = churchDescCountry.Default.(string)
	// churchDescCongregationSize is the schema descriptor for congregation_size field.
	churchDescCongregationSize := churchFields[17].Descriptor()
	// church.DefaultCongregationSize holds the default value on creation for the congregation_size field.
	church.DefaultCongregationSize = churchDescCongregationSize.Default.(int)
	// churchDescIsActive is the schema descriptor for is_active field.
	churchDescIsActive := churchFields[18].Descriptor()
	// church.DefaultIsActive holds the default value on creation for the is_active field.
	church.DefaultIsActive = churchDescIsActive.Default.(bool)
	// churchDescCreatedAt is the schema descriptor for created_at field.
	churchDescCreatedAt := churchFields[19].Descriptor()
	// church.DefaultCreatedAt holds the default value on creation for the created_at field.
	church.DefaultCreatedAt = churchDescCreatedAt.Default.(func() time.Time)
	// churchDescUpdatedAt is the schema descriptor for updated_at field.
	churchDescUpdatedAt := churchFields[20].Descriptor()
	// church.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	church.DefaultUpdatedAt = churchDescUpdatedAt.Default.(func() time.Time)
	// church.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	church.UpdateDefaultUpdatedAt = churchDescUpdatedAt.UpdateDefault.(func() time.Time)
	communicationFields := schema.Communication{}.Fields()
	_ = communicationFields
	// communicationDescRecipientFilter is the schema descriptor for recipient_filter field.
	communicationDescRecipientFilter := communicationFields[2].Descriptor()
	// communication.DefaultRecipientFilter holds the default value on creation for the recipient_filter field.
	communication.DefaultRecipientFilter = communicationDescRecipientFilter.Default.(string)
	// communicationDescRecipientFilterLabel is the schema descriptor for recipient_filter_label field.
	communicationDescRecipientFilterLabel := communicationFields[3].Descriptor()
	// communication.DefaultRecipientFilterLabel holds the default value on creation for the recipient_filter_label field.
	communication.DefaultRecipientFilterLabel = communicationDescRecipientFilterLabel.Default.(string)
	// communicationDescRecipientCount is the schema descriptor for recipient_count field.
	communicationDescRecipientCount := communicationFields[4].Descriptor()
	// communication.DefaultRecipientCount holds the default value on creation for the recipient_count field.
	communication.DefaultRecipientCount = communicationDescRecipientCount.Default.(int)
	// communicationDescSentCount is the schema descriptor for sent_count field.
	communicationDescSentCount := communicationFields[5].Descriptor()
	// communication.DefaultSentCount holds the default value on creation for the sent_count field.
	communication.DefaultSentCount = communicationDescSentCount.Default.(int)
	// communicationDescFailCount is the schema descriptor for fail_count field.
	communicationDescFailCount := communicationFields[6].Descriptor()
	// communication.DefaultFailCount holds the default value on creation for the fail_count field.
	communication.DefaultFailCount = communicationDescFailCount.Default.(int)
	// communicationDescSentAt is the schema descriptor for sent_at field.
	communicationDescSentAt := communicationFields[7].Descriptor()
	// communication.DefaultSentAt holds the default value on creation for the sent_at field.
	communication.DefaultSentAt = communicationDescSentAt.Default.(func() time.Time)
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescHasSpouse is the schema descriptor for has_spouse field.
	contactDescHasSpouse := contactFields[26].Descriptor()
	// contact.DefaultHasSpouse holds the default value on creation for the has_spouse field.
	contact.DefaultHasSpouse = contactDescHasSpouse.Default.(bool)
	// contactDescIsBaptized is the schema descriptor for is_baptized field.
	contactDescIsBaptized := contactFields[29].Descriptor()
	// contact.DefaultIsBaptized holds the default value on creation for the is_baptized field.
	contact.DefaultIsBaptized = contactDescIsBaptized.Default.(bool)
	// contactDescCreatedAt is the schema descriptor for created_at field.
	contactDescCreatedAt := contactFields[34].Descriptor()
	// contact.DefaultCreatedAt holds the default value on creation for the created_at field.
	contact.DefaultCreatedAt = contactDescCreatedAt.Default.(func() time.Time)
	// contactDescUpdatedAt is the schema descriptor for updated_at field.
	contactDescUpdatedAt := contactFields[35].Descriptor()
	// contact.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contact.DefaultUpdatedAt = contactDescUpdatedAt.Default.(func() time.Time)
	// contact.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	contact.UpdateDefaultUpdatedAt = contactDescUpdatedAt.UpdateDefault.(func() time.Time)
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescIsActive is the schema descriptor for is_active field.
	departmentDescIsActive := departmentFields[3].Descriptor()
	// department.DefaultIsActive holds the default value on creation for the is_active field.
	department.DefaultIsActive = departmentDescIsActive.Default.(bool)
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentFields[6].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	// departmentDescUpdatedAt is the schema descriptor for updated_at field.
	departmentDescUpdatedAt := departmentFields[7].Descriptor()
	// department.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	department.DefaultUpdatedAt = departmentDescUpdatedAt.Default.(func() time.Time)
	// department.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	department.UpdateDefaultUpdatedAt = departmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescIsPublic is the schema descriptor for is_public field.
	documentDescIsPublic := documentFields[7].Descriptor()
	// document.DefaultIsPublic holds the default value on creation for the is_public field.
	document.DefaultIsPublic = documentDescIsPublic.Default.(bool)
	// documentDescCreatedAt is the schema descriptor for created_at field.
	documentDescCreatedAt := documentFields[9].Descriptor()
	// document.DefaultCreatedAt holds the default value on creation for the created_at field.
	document.DefaultCreatedAt = documentDescCreatedAt.Default.(func() time.Time)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescAttendanceCount is the schema descriptor for attendance_count field.
	eventDescAttendanceCount := eventFields[6].Descriptor()
	// event.DefaultAttendanceCount holds the default value on creation for the attendance_count field.
	event.DefaultAttendanceCount = eventDescAttendanceCount.Default.(int)
	// eventDescIsPublished is the schema descriptor for is_published field.
	eventDescIsPublished := eventFields[8].Descriptor()
	// event.DefaultIsPublished holds the default value on creation for the is_published field.
	event.DefaultIsPublished = eventDescIsPublished.Default.(bool)
	financeFields := schema.Finance{}.Fields()
	_ = financeFields
	// financeDescCurrency is the schema descriptor for currency field.
	financeDescCurrency := financeFields[3].Descriptor()
	// finance.DefaultCurrency holds the default value on creation for the currency field.
	finance.DefaultCurrency = financeDescCurrency.Default.(string)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescIsActive is the schema descriptor for is_active field.
	groupDescIsActive := groupFields[6].Descriptor()
	// group.DefaultIsActive holds the default value on creation for the is_active field.
	group.DefaultIsActive = groupDescIsActive.Default.(bool)
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[9].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupFields[10].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	invitationFields := schema.Invitation{}.Fields()
	_ = invitationFields
	// invitationDescCreatedAt is the schema descriptor for created_at field.
	invitationDescCreatedAt := invitationFields[6].Descriptor()
	// invitation.DefaultCreatedAt holds the default value on creation for the created_at field.
	invitation.DefaultCreatedAt = invitationDescCreatedAt.Default.(func() time.Time)
	// invitationDescUpdatedAt is the schema descriptor for updated_at field.
	invitationDescUpdatedAt := invitationFields[7].Descriptor()
	// invitation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invitation.DefaultUpdatedAt = invitationDescUpdatedAt.Default.(func() time.Time)
	// invitation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invitation.UpdateDefaultUpdatedAt = invitationDescUpdatedAt.UpdateDefault.(func() time.Time)
	milestoneFields := schema.Milestone{}.Fields()
	_ = milestoneFields
	// milestoneDescCreatedAt is the schema descriptor for created_at field.
	milestoneDescCreatedAt := milestoneFields[6].Descriptor()
	// milestone.DefaultCreatedAt holds the default value on creation for the created_at field.
	milestone.DefaultCreatedAt = milestoneDescCreatedAt.Default.(func() time.Time)
	pastoralnoteFields := schema.PastoralNote{}.Fields()
	_ = pastoralnoteFields
	// pastoralnoteDescNeedsFollowUp is the schema descriptor for needs_follow_up field.
	pastoralnoteDescNeedsFollowUp := pastoralnoteFields[3].Descriptor()
	// pastoralnote.DefaultNeedsFollowUp holds the default value on creation for the needs_follow_up field.
	pastoralnote.DefaultNeedsFollowUp = pastoralnoteDescNeedsFollowUp.Default.(bool)
	// pastoralnoteDescFollowUpDone is the schema descriptor for follow_up_done field.
	pastoralnoteDescFollowUpDone := pastoralnoteFields[5].Descriptor()
	// pastoralnote.DefaultFollowUpDone holds the default value on creation for the follow_up_done field.
	pastoralnote.DefaultFollowUpDone = pastoralnoteDescFollowUpDone.Default.(bool)
	// pastoralnoteDescCreatedAt is the schema descriptor for created_at field.
	pastoralnoteDescCreatedAt := pastoralnoteFields[9].Descriptor()
	// pastoralnote.DefaultCreatedAt holds the default value on creation for the created_at field.
	pastoralnote.DefaultCreatedAt = pastoralnoteDescCreatedAt.Default.(func() time.Time)
	// pastoralnoteDescUpdatedAt is the schema descriptor for updated_at field.
	pastoralnoteDescUpdatedAt := pastoralnoteFields[10].Descriptor()
	// pastoralnote.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pastoralnote.DefaultUpdatedAt = pastoralnoteDescUpdatedAt.Default.(func() time.Time)
	// pastoralnote.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pastoralnote.UpdateDefaultUpdatedAt = pastoralnoteDescUpdatedAt.UpdateDefault.(func() time.Time)
	pledgeFields := schema.Pledge{}.Fields()
	_ = pledgeFields
	// pledgeDescCategory is the schema descriptor for category field.
	pledgeDescCategory := pledgeFields[3].Descriptor()
	// pledge.DefaultCategory holds the default value on creation for the category field.
	pledge.DefaultCategory = pledgeDescCategory.Default.(string)
	// pledgeDescCurrency is the schema descriptor for currency field.
	pledgeDescCurrency := pledgeFields[5].Descriptor()
	// pledge.DefaultCurrency holds the default value on creation for the currency field.
	pledge.DefaultCurrency = pledgeDescCurrency.Default.(string)
	// pledgeDescCreatedAt is the schema descriptor for created_at field.
	pledgeDescCreatedAt := pledgeFields[10].Descriptor()
	// pledge.DefaultCreatedAt holds the default value on creation for the created_at field.
	pledge.DefaultCreatedAt = pledgeDescCreatedAt.Default.(func() time.Time)
	prayerrequestFields := schema.PrayerRequest{}.Fields()
	_ = prayerrequestFields
	// prayerrequestDescIsAnonymous is the schema descriptor for is_anonymous field.
	prayerrequestDescIsAnonymous := prayerrequestFields[3].Descriptor()
	// prayerrequest.DefaultIsAnonymous holds the default value on creation for the is_anonymous field.
	prayerrequest.DefaultIsAnonymous = prayerrequestDescIsAnonymous.Default.(bool)
	// prayerrequestDescIsPrivate is the schema descriptor for is_private field.
	prayerrequestDescIsPrivate := prayerrequestFields[4].Descriptor()
	// prayerrequest.DefaultIsPrivate holds the default value on creation for the is_private field.
	prayerrequest.DefaultIsPrivate = prayerrequestDescIsPrivate.Default.(bool)
	// prayerrequestDescCreatedAt is the schema descriptor for created_at field.
	prayerrequestDescCreatedAt := prayerrequestFields[8].Descriptor()
	// prayerrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	prayerrequest.DefaultCreatedAt = prayerrequestDescCreatedAt.Default.(func() time.Time)
	// prayerrequestDescUpdatedAt is the schema descriptor for updated_at field.
	prayerrequestDescUpdatedAt := prayerrequestFields[9].Descriptor()
	// prayerrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	prayerrequest.DefaultUpdatedAt = prayerrequestDescUpdatedAt.Default.(func() time.Time)
	// prayerrequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	prayerrequest.UpdateDefaultUpdatedAt = prayerrequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	programentryFields := schema.ProgramEntry{}.Fields()
	_ = programentryFields
	// programentryDescIsPublished is the schema descriptor for is_published field.
	programentryDescIsPublished := programentryFields[12].Descriptor()
	// programentry.DefaultIsPublished holds the default value on creation for the is_published field.
	programentry.DefaultIsPublished = programentryDescIsPublished.Default.(bool)
	// programentryDescCreatedAt is the schema descriptor for created_at field.
	programentryDescCreatedAt := programentryFields[13].Descriptor()
	// programentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	programentry.DefaultCreatedAt = programentryDescCreatedAt.Default.(func() time.Time)
	relationshipFields := schema.Relationship{}.Fields()
	_ = relationshipFields
	// relationshipDescCreatedAt is the schema descriptor for created_at field.
	relationshipDescCreatedAt := relationshipFields[4].Descriptor()
	// relationship.DefaultCreatedAt holds the default value on creation for the created_at field.
	relationship.DefaultCreatedAt = relationshipDescCreatedAt.Default.(func() time.Time)
	rosterFields := schema.Roster{}.Fields()
	_ = rosterFields
	// rosterDescCreatedAt is the schema descriptor for created_at field.
	rosterDescCreatedAt := rosterFields[5].Descriptor()
	// roster.DefaultCreatedAt holds the default value on creation for the created_at field.
	roster.DefaultCreatedAt = rosterDescCreatedAt.Default.(func() time.Time)
	sermonFields := schema.Sermon{}.Fields()
	_ = sermonFields
	// sermonDescIsPublished is the schema descriptor for is_published field.
	sermonDescIsPublished := sermonFields[7].Descriptor()
	// sermon.DefaultIsPublished holds the default value on creation for the is_published field.
	sermon.DefaultIsPublished = sermonDescIsPublished.Default.(bool)
	// sermonDescCreatedAt is the schema descriptor for created_at field.
	sermonDescCreatedAt := sermonFields[9].Descriptor()
	// sermon.DefaultCreatedAt holds the default value on creation for the created_at field.
	sermon.DefaultCreatedAt = sermonDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[0].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = func() func(string) error {
		validators := sessionDescToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token string) error {
			for _, fn := range fns {
				if err := fn(token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sessionDescData is the schema descriptor for data field.
	sessionDescData := sessionFields[1].Descriptor()
	// session.DataValidator is a validator for the "data" field. It is called by the builders before save.
	session.DataValidator = sessionDescData.Validators[0].(func([]byte) error)
	// sessionDescExpiry is the schema descriptor for expiry field.
	sessionDescExpiry := sessionFields[2].Descriptor()
	// session.DefaultExpiry holds the default value on creation for the expiry field.
	session.DefaultExpiry = sessionDescExpiry.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[3].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	visitorFields := schema.Visitor{}.Fields()
	_ = visitorFields
	// visitorDescCreatedAt is the schema descriptor for created_at field.
	visitorDescCreatedAt := visitorFields[11].Descriptor()
	// visitor.DefaultCreatedAt holds the default value on creation for the created_at field.
	visitor.DefaultCreatedAt = visitorDescCreatedAt.Default.(func() time.Time)
}
