// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/invitation"
	"github.com/ntiGideon/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// Role holds the value of the "role" field.
	Role user.Role `json:"role,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// LastLogin holds the value of the "last_login" field.
	LastLogin time.Time `json:"last_login,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges                    UserEdges `json:"edges"`
	church_users             *int
	contact_user             *int
	invitation_accepted_user *int
	selectValues             sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Church holds the value of the church edge.
	Church *Church `json:"church,omitempty"`
	// Contact holds the value of the contact edge.
	Contact *Contact `json:"contact,omitempty"`
	// FinanceRecords holds the value of the finance_records edge.
	FinanceRecords []*Finance `json:"finance_records,omitempty"`
	// SentInvitations holds the value of the sent_invitations edge.
	SentInvitations []*Invitation `json:"sent_invitations,omitempty"`
	// Announcements holds the value of the announcements edge.
	Announcements []*Announcement `json:"announcements,omitempty"`
	// AcceptedInvitation holds the value of the accepted_invitation edge.
	AcceptedInvitation *Invitation `json:"accepted_invitation,omitempty"`
	// PastoralNotesRecorded holds the value of the pastoral_notes_recorded edge.
	PastoralNotesRecorded []*PastoralNote `json:"pastoral_notes_recorded,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// ChurchOrErr returns the Church value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) ChurchOrErr() (*Church, error) {
	if e.Church != nil {
		return e.Church, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: church.Label}
	}
	return nil, &NotLoadedError{edge: "church"}
}

// ContactOrErr returns the Contact value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) ContactOrErr() (*Contact, error) {
	if e.Contact != nil {
		return e.Contact, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: contact.Label}
	}
	return nil, &NotLoadedError{edge: "contact"}
}

// FinanceRecordsOrErr returns the FinanceRecords value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FinanceRecordsOrErr() ([]*Finance, error) {
	if e.loadedTypes[2] {
		return e.FinanceRecords, nil
	}
	return nil, &NotLoadedError{edge: "finance_records"}
}

// SentInvitationsOrErr returns the SentInvitations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SentInvitationsOrErr() ([]*Invitation, error) {
	if e.loadedTypes[3] {
		return e.SentInvitations, nil
	}
	return nil, &NotLoadedError{edge: "sent_invitations"}
}

// AnnouncementsOrErr returns the Announcements value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AnnouncementsOrErr() ([]*Announcement, error) {
	if e.loadedTypes[4] {
		return e.Announcements, nil
	}
	return nil, &NotLoadedError{edge: "announcements"}
}

// AcceptedInvitationOrErr returns the AcceptedInvitation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) AcceptedInvitationOrErr() (*Invitation, error) {
	if e.AcceptedInvitation != nil {
		return e.AcceptedInvitation, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: invitation.Label}
	}
	return nil, &NotLoadedError{edge: "accepted_invitation"}
}

// PastoralNotesRecordedOrErr returns the PastoralNotesRecorded value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PastoralNotesRecordedOrErr() ([]*PastoralNote, error) {
	if e.loadedTypes[6] {
		return e.PastoralNotesRecorded, nil
	}
	return nil, &NotLoadedError{edge: "pastoral_notes_recorded"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIsActive:
			values[i] = new(sql.NullBool)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail, user.FieldPasswordHash, user.FieldRole:
			values[i] = new(sql.NullString)
		case user.FieldLastLogin, user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.ForeignKeys[0]: // church_users
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[1]: // contact_user
			values[i] = new(sql.NullInt64)
		case user.ForeignKeys[2]: // invitation_accepted_user
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = user.Role(value.String)
			}
		case user.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case user.FieldLastLogin:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login", values[i])
			} else if value.Valid {
				_m.LastLogin = value.Time
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field church_users", value)
			} else if value.Valid {
				_m.church_users = new(int)
				*_m.church_users = int(value.Int64)
			}
		case user.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field contact_user", value)
			} else if value.Valid {
				_m.contact_user = new(int)
				*_m.contact_user = int(value.Int64)
			}
		case user.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field invitation_accepted_user", value)
			} else if value.Valid {
				_m.invitation_accepted_user = new(int)
				*_m.invitation_accepted_user = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChurch queries the "church" edge of the User entity.
func (_m *User) QueryChurch() *ChurchQuery {
	return NewUserClient(_m.config).QueryChurch(_m)
}

// QueryContact queries the "contact" edge of the User entity.
func (_m *User) QueryContact() *ContactQuery {
	return NewUserClient(_m.config).QueryContact(_m)
}

// QueryFinanceRecords queries the "finance_records" edge of the User entity.
func (_m *User) QueryFinanceRecords() *FinanceQuery {
	return NewUserClient(_m.config).QueryFinanceRecords(_m)
}

// QuerySentInvitations queries the "sent_invitations" edge of the User entity.
func (_m *User) QuerySentInvitations() *InvitationQuery {
	return NewUserClient(_m.config).QuerySentInvitations(_m)
}

// QueryAnnouncements queries the "announcements" edge of the User entity.
func (_m *User) QueryAnnouncements() *AnnouncementQuery {
	return NewUserClient(_m.config).QueryAnnouncements(_m)
}

// QueryAcceptedInvitation queries the "accepted_invitation" edge of the User entity.
func (_m *User) QueryAcceptedInvitation() *InvitationQuery {
	return NewUserClient(_m.config).QueryAcceptedInvitation(_m)
}

// QueryPastoralNotesRecorded queries the "pastoral_notes_recorded" edge of the User entity.
func (_m *User) QueryPastoralNotesRecorded() *PastoralNoteQuery {
	return NewUserClient(_m.config).QueryPastoralNotesRecorded(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("last_login=")
	builder.WriteString(_m.LastLogin.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
