// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/ent/announcement"
	"github.com/ntiGideon/ent/church"
	"github.com/ntiGideon/ent/contact"
	"github.com/ntiGideon/ent/finance"
	"github.com/ntiGideon/ent/invitation"
	"github.com/ntiGideon/ent/pastoralnote"
	"github.com/ntiGideon/ent/predicate"
	"github.com/ntiGideon/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdate) SetRole(v user.Role) *UserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRole(v *user.Role) *UserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdate) SetIsActive(v bool) *UserUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsActive(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *UserUpdate) SetLastLogin(v time.Time) *UserUpdate {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLogin(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *UserUpdate) ClearLastLogin() *UserUpdate {
	_u.mutation.ClearLastLogin()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChurchID sets the "church" edge to the Church entity by ID.
func (_u *UserUpdate) SetChurchID(id int) *UserUpdate {
	_u.mutation.SetChurchID(id)
	return _u
}

// SetNillableChurchID sets the "church" edge to the Church entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableChurchID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetChurchID(*id)
	}
	return _u
}

// SetChurch sets the "church" edge to the Church entity.
func (_u *UserUpdate) SetChurch(v *Church) *UserUpdate {
	return _u.SetChurchID(v.ID)
}

// SetContactID sets the "contact" edge to the Contact entity by ID.
func (_u *UserUpdate) SetContactID(id int) *UserUpdate {
	_u.mutation.SetContactID(id)
	return _u
}

// SetContact sets the "contact" edge to the Contact entity.
func (_u *UserUpdate) SetContact(v *Contact) *UserUpdate {
	return _u.SetContactID(v.ID)
}

// AddFinanceRecordIDs adds the "finance_records" edge to the Finance entity by IDs.
func (_u *UserUpdate) AddFinanceRecordIDs(ids ...int) *UserUpdate {
	_u.mutation.AddFinanceRecordIDs(ids...)
	return _u
}

// AddFinanceRecords adds the "finance_records" edges to the Finance entity.
func (_u *UserUpdate) AddFinanceRecords(v ...*Finance) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFinanceRecordIDs(ids...)
}

// AddSentInvitationIDs adds the "sent_invitations" edge to the Invitation entity by IDs.
func (_u *UserUpdate) AddSentInvitationIDs(ids ...int) *UserUpdate {
	_u.mutation.AddSentInvitationIDs(ids...)
	return _u
}

// AddSentInvitations adds the "sent_invitations" edges to the Invitation entity.
func (_u *UserUpdate) AddSentInvitations(v ...*Invitation) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentInvitationIDs(ids...)
}

// AddAnnouncementIDs adds the "announcements" edge to the Announcement entity by IDs.
func (_u *UserUpdate) AddAnnouncementIDs(ids ...int) *UserUpdate {
	_u.mutation.AddAnnouncementIDs(ids...)
	return _u
}

// AddAnnouncements adds the "announcements" edges to the Announcement entity.
func (_u *UserUpdate) AddAnnouncements(v ...*Announcement) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnouncementIDs(ids...)
}

// SetAcceptedInvitationID sets the "accepted_invitation" edge to the Invitation entity by ID.
func (_u *UserUpdate) SetAcceptedInvitationID(id int) *UserUpdate {
	_u.mutation.SetAcceptedInvitationID(id)
	return _u
}

// SetNillableAcceptedInvitationID sets the "accepted_invitation" edge to the Invitation entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableAcceptedInvitationID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetAcceptedInvitationID(*id)
	}
	return _u
}

// SetAcceptedInvitation sets the "accepted_invitation" edge to the Invitation entity.
func (_u *UserUpdate) SetAcceptedInvitation(v *Invitation) *UserUpdate {
	return _u.SetAcceptedInvitationID(v.ID)
}

// AddPastoralNotesRecordedIDs adds the "pastoral_notes_recorded" edge to the PastoralNote entity by IDs.
func (_u *UserUpdate) AddPastoralNotesRecordedIDs(ids ...int) *UserUpdate {
	_u.mutation.AddPastoralNotesRecordedIDs(ids...)
	return _u
}

// AddPastoralNotesRecorded adds the "pastoral_notes_recorded" edges to the PastoralNote entity.
func (_u *UserUpdate) AddPastoralNotesRecorded(v ...*PastoralNote) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPastoralNotesRecordedIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the Church entity.
func (_u *UserUpdate) ClearChurch() *UserUpdate {
	_u.mutation.ClearChurch()
	return _u
}

// ClearContact clears the "contact" edge to the Contact entity.
func (_u *UserUpdate) ClearContact() *UserUpdate {
	_u.mutation.ClearContact()
	return _u
}

// ClearFinanceRecords clears all "finance_records" edges to the Finance entity.
func (_u *UserUpdate) ClearFinanceRecords() *UserUpdate {
	_u.mutation.ClearFinanceRecords()
	return _u
}

// RemoveFinanceRecordIDs removes the "finance_records" edge to Finance entities by IDs.
func (_u *UserUpdate) RemoveFinanceRecordIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveFinanceRecordIDs(ids...)
	return _u
}

// RemoveFinanceRecords removes "finance_records" edges to Finance entities.
func (_u *UserUpdate) RemoveFinanceRecords(v ...*Finance) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFinanceRecordIDs(ids...)
}

// ClearSentInvitations clears all "sent_invitations" edges to the Invitation entity.
func (_u *UserUpdate) ClearSentInvitations() *UserUpdate {
	_u.mutation.ClearSentInvitations()
	return _u
}

// RemoveSentInvitationIDs removes the "sent_invitations" edge to Invitation entities by IDs.
func (_u *UserUpdate) RemoveSentInvitationIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveSentInvitationIDs(ids...)
	return _u
}

// RemoveSentInvitations removes "sent_invitations" edges to Invitation entities.
func (_u *UserUpdate) RemoveSentInvitations(v ...*Invitation) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentInvitationIDs(ids...)
}

// ClearAnnouncements clears all "announcements" edges to the Announcement entity.
func (_u *UserUpdate) ClearAnnouncements() *UserUpdate {
	_u.mutation.ClearAnnouncements()
	return _u
}

// RemoveAnnouncementIDs removes the "announcements" edge to Announcement entities by IDs.
func (_u *UserUpdate) RemoveAnnouncementIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveAnnouncementIDs(ids...)
	return _u
}

// RemoveAnnouncements removes "announcements" edges to Announcement entities.
func (_u *UserUpdate) RemoveAnnouncements(v ...*Announcement) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnouncementIDs(ids...)
}

// ClearAcceptedInvitation clears the "accepted_invitation" edge to the Invitation entity.
func (_u *UserUpdate) ClearAcceptedInvitation() *UserUpdate {
	_u.mutation.ClearAcceptedInvitation()
	return _u
}

// ClearPastoralNotesRecorded clears all "pastoral_notes_recorded" edges to the PastoralNote entity.
func (_u *UserUpdate) ClearPastoralNotesRecorded() *UserUpdate {
	_u.mutation.ClearPastoralNotesRecorded()
	return _u
}

// RemovePastoralNotesRecordedIDs removes the "pastoral_notes_recorded" edge to PastoralNote entities by IDs.
func (_u *UserUpdate) RemovePastoralNotesRecordedIDs(ids ...int) *UserUpdate {
	_u.mutation.RemovePastoralNotesRecordedIDs(ids...)
	return _u
}

// RemovePastoralNotesRecorded removes "pastoral_notes_recorded" edges to PastoralNote entities.
func (_u *UserUpdate) RemovePastoralNotesRecorded(v ...*PastoralNote) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePastoralNotesRecordedIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if _u.mutation.ContactCleared() && len(_u.mutation.ContactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "User.contact"`)
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(user.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(user.FieldLastLogin, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ChurchTable,
			Columns: []string{user.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ChurchTable,
			Columns: []string{user.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.ContactTable,
			Columns: []string{user.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.ContactTable,
			Columns: []string{user.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FinanceRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FinanceRecordsTable,
			Columns: []string{user.FinanceRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFinanceRecordsIDs(); len(nodes) > 0 && !_u.mutation.FinanceRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FinanceRecordsTable,
			Columns: []string{user.FinanceRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FinanceRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FinanceRecordsTable,
			Columns: []string{user.FinanceRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentInvitationsIDs(); len(nodes) > 0 && !_u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentInvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnnouncementsTable,
			Columns: []string{user.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnouncementsIDs(); len(nodes) > 0 && !_u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnnouncementsTable,
			Columns: []string{user.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnnouncementsTable,
			Columns: []string{user.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AcceptedInvitationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.AcceptedInvitationTable,
			Columns: []string{user.AcceptedInvitationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AcceptedInvitationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.AcceptedInvitationTable,
			Columns: []string{user.AcceptedInvitationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PastoralNotesRecordedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PastoralNotesRecordedTable,
			Columns: []string{user.PastoralNotesRecordedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPastoralNotesRecordedIDs(); len(nodes) > 0 && !_u.mutation.PastoralNotesRecordedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PastoralNotesRecordedTable,
			Columns: []string{user.PastoralNotesRecordedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PastoralNotesRecordedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PastoralNotesRecordedTable,
			Columns: []string{user.PastoralNotesRecordedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdateOne) SetRole(v user.Role) *UserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRole(v *user.Role) *UserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdateOne) SetIsActive(v bool) *UserUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsActive(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *UserUpdateOne) SetLastLogin(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLogin(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// ClearLastLogin clears the value of the "last_login" field.
func (_u *UserUpdateOne) ClearLastLogin() *UserUpdateOne {
	_u.mutation.ClearLastLogin()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChurchID sets the "church" edge to the Church entity by ID.
func (_u *UserUpdateOne) SetChurchID(id int) *UserUpdateOne {
	_u.mutation.SetChurchID(id)
	return _u
}

// SetNillableChurchID sets the "church" edge to the Church entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableChurchID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetChurchID(*id)
	}
	return _u
}

// SetChurch sets the "church" edge to the Church entity.
func (_u *UserUpdateOne) SetChurch(v *Church) *UserUpdateOne {
	return _u.SetChurchID(v.ID)
}

// SetContactID sets the "contact" edge to the Contact entity by ID.
func (_u *UserUpdateOne) SetContactID(id int) *UserUpdateOne {
	_u.mutation.SetContactID(id)
	return _u
}

// SetContact sets the "contact" edge to the Contact entity.
func (_u *UserUpdateOne) SetContact(v *Contact) *UserUpdateOne {
	return _u.SetContactID(v.ID)
}

// AddFinanceRecordIDs adds the "finance_records" edge to the Finance entity by IDs.
func (_u *UserUpdateOne) AddFinanceRecordIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddFinanceRecordIDs(ids...)
	return _u
}

// AddFinanceRecords adds the "finance_records" edges to the Finance entity.
func (_u *UserUpdateOne) AddFinanceRecords(v ...*Finance) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFinanceRecordIDs(ids...)
}

// AddSentInvitationIDs adds the "sent_invitations" edge to the Invitation entity by IDs.
func (_u *UserUpdateOne) AddSentInvitationIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddSentInvitationIDs(ids...)
	return _u
}

// AddSentInvitations adds the "sent_invitations" edges to the Invitation entity.
func (_u *UserUpdateOne) AddSentInvitations(v ...*Invitation) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentInvitationIDs(ids...)
}

// AddAnnouncementIDs adds the "announcements" edge to the Announcement entity by IDs.
func (_u *UserUpdateOne) AddAnnouncementIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddAnnouncementIDs(ids...)
	return _u
}

// AddAnnouncements adds the "announcements" edges to the Announcement entity.
func (_u *UserUpdateOne) AddAnnouncements(v ...*Announcement) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnouncementIDs(ids...)
}

// SetAcceptedInvitationID sets the "accepted_invitation" edge to the Invitation entity by ID.
func (_u *UserUpdateOne) SetAcceptedInvitationID(id int) *UserUpdateOne {
	_u.mutation.SetAcceptedInvitationID(id)
	return _u
}

// SetNillableAcceptedInvitationID sets the "accepted_invitation" edge to the Invitation entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAcceptedInvitationID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetAcceptedInvitationID(*id)
	}
	return _u
}

// SetAcceptedInvitation sets the "accepted_invitation" edge to the Invitation entity.
func (_u *UserUpdateOne) SetAcceptedInvitation(v *Invitation) *UserUpdateOne {
	return _u.SetAcceptedInvitationID(v.ID)
}

// AddPastoralNotesRecordedIDs adds the "pastoral_notes_recorded" edge to the PastoralNote entity by IDs.
func (_u *UserUpdateOne) AddPastoralNotesRecordedIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddPastoralNotesRecordedIDs(ids...)
	return _u
}

// AddPastoralNotesRecorded adds the "pastoral_notes_recorded" edges to the PastoralNote entity.
func (_u *UserUpdateOne) AddPastoralNotesRecorded(v ...*PastoralNote) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPastoralNotesRecordedIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the Church entity.
func (_u *UserUpdateOne) ClearChurch() *UserUpdateOne {
	_u.mutation.ClearChurch()
	return _u
}

// ClearContact clears the "contact" edge to the Contact entity.
func (_u *UserUpdateOne) ClearContact() *UserUpdateOne {
	_u.mutation.ClearContact()
	return _u
}

// ClearFinanceRecords clears all "finance_records" edges to the Finance entity.
func (_u *UserUpdateOne) ClearFinanceRecords() *UserUpdateOne {
	_u.mutation.ClearFinanceRecords()
	return _u
}

// RemoveFinanceRecordIDs removes the "finance_records" edge to Finance entities by IDs.
func (_u *UserUpdateOne) RemoveFinanceRecordIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveFinanceRecordIDs(ids...)
	return _u
}

// RemoveFinanceRecords removes "finance_records" edges to Finance entities.
func (_u *UserUpdateOne) RemoveFinanceRecords(v ...*Finance) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFinanceRecordIDs(ids...)
}

// ClearSentInvitations clears all "sent_invitations" edges to the Invitation entity.
func (_u *UserUpdateOne) ClearSentInvitations() *UserUpdateOne {
	_u.mutation.ClearSentInvitations()
	return _u
}

// RemoveSentInvitationIDs removes the "sent_invitations" edge to Invitation entities by IDs.
func (_u *UserUpdateOne) RemoveSentInvitationIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveSentInvitationIDs(ids...)
	return _u
}

// RemoveSentInvitations removes "sent_invitations" edges to Invitation entities.
func (_u *UserUpdateOne) RemoveSentInvitations(v ...*Invitation) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentInvitationIDs(ids...)
}

// ClearAnnouncements clears all "announcements" edges to the Announcement entity.
func (_u *UserUpdateOne) ClearAnnouncements() *UserUpdateOne {
	_u.mutation.ClearAnnouncements()
	return _u
}

// RemoveAnnouncementIDs removes the "announcements" edge to Announcement entities by IDs.
func (_u *UserUpdateOne) RemoveAnnouncementIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveAnnouncementIDs(ids...)
	return _u
}

// RemoveAnnouncements removes "announcements" edges to Announcement entities.
func (_u *UserUpdateOne) RemoveAnnouncements(v ...*Announcement) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnouncementIDs(ids...)
}

// ClearAcceptedInvitation clears the "accepted_invitation" edge to the Invitation entity.
func (_u *UserUpdateOne) ClearAcceptedInvitation() *UserUpdateOne {
	_u.mutation.ClearAcceptedInvitation()
	return _u
}

// ClearPastoralNotesRecorded clears all "pastoral_notes_recorded" edges to the PastoralNote entity.
func (_u *UserUpdateOne) ClearPastoralNotesRecorded() *UserUpdateOne {
	_u.mutation.ClearPastoralNotesRecorded()
	return _u
}

// RemovePastoralNotesRecordedIDs removes the "pastoral_notes_recorded" edge to PastoralNote entities by IDs.
func (_u *UserUpdateOne) RemovePastoralNotesRecordedIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemovePastoralNotesRecordedIDs(ids...)
	return _u
}

// RemovePastoralNotesRecorded removes "pastoral_notes_recorded" edges to PastoralNote entities.
func (_u *UserUpdateOne) RemovePastoralNotesRecorded(v ...*PastoralNote) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePastoralNotesRecordedIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if _u.mutation.ContactCleared() && len(_u.mutation.ContactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "User.contact"`)
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(user.FieldLastLogin, field.TypeTime, value)
	}
	if _u.mutation.LastLoginCleared() {
		_spec.ClearField(user.FieldLastLogin, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ChurchTable,
			Columns: []string{user.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ChurchTable,
			Columns: []string{user.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(church.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.ContactTable,
			Columns: []string{user.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.ContactTable,
			Columns: []string{user.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FinanceRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FinanceRecordsTable,
			Columns: []string{user.FinanceRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFinanceRecordsIDs(); len(nodes) > 0 && !_u.mutation.FinanceRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FinanceRecordsTable,
			Columns: []string{user.FinanceRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FinanceRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FinanceRecordsTable,
			Columns: []string{user.FinanceRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentInvitationsIDs(); len(nodes) > 0 && !_u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentInvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnnouncementsTable,
			Columns: []string{user.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnouncementsIDs(); len(nodes) > 0 && !_u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnnouncementsTable,
			Columns: []string{user.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnnouncementsTable,
			Columns: []string{user.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AcceptedInvitationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.AcceptedInvitationTable,
			Columns: []string{user.AcceptedInvitationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AcceptedInvitationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   user.AcceptedInvitationTable,
			Columns: []string{user.AcceptedInvitationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PastoralNotesRecordedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PastoralNotesRecordedTable,
			Columns: []string{user.PastoralNotesRecordedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPastoralNotesRecordedIDs(); len(nodes) > 0 && !_u.mutation.PastoralNotesRecordedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PastoralNotesRecordedTable,
			Columns: []string{user.PastoralNotesRecordedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PastoralNotesRecordedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PastoralNotesRecordedTable,
			Columns: []string{user.PastoralNotesRecordedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pastoralnote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
