// Code generated by ent, DO NOT EDIT.

package relationship

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relationship type in the database.
	Label = "relationship"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFromContactID holds the string denoting the from_contact_id field in the database.
	FieldFromContactID = "from_contact_id"
	// FieldToContactID holds the string denoting the to_contact_id field in the database.
	FieldToContactID = "to_contact_id"
	// FieldRelationType holds the string denoting the relation_type field in the database.
	FieldRelationType = "relation_type"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeFromContact holds the string denoting the from_contact edge name in mutations.
	EdgeFromContact = "from_contact"
	// EdgeToContact holds the string denoting the to_contact edge name in mutations.
	EdgeToContact = "to_contact"
	// Table holds the table name of the relationship in the database.
	Table = "relationships"
	// FromContactTable is the table that holds the from_contact relation/edge.
	FromContactTable = "relationships"
	// FromContactInverseTable is the table name for the Contact entity.
	// It exists in this package in order to avoid circular dependency with the "contact" package.
	FromContactInverseTable = "contacts"
	// FromContactColumn is the table column denoting the from_contact relation/edge.
	FromContactColumn = "from_contact_id"
	// ToContactTable is the table that holds the to_contact relation/edge.
	ToContactTable = "relationships"
	// ToContactInverseTable is the table name for the Contact entity.
	// It exists in this package in order to avoid circular dependency with the "contact" package.
	ToContactInverseTable = "contacts"
	// ToContactColumn is the table column denoting the to_contact relation/edge.
	ToContactColumn = "to_contact_id"
)

// Columns holds all SQL columns for relationship fields.
var Columns = []string{
	FieldID,
	FieldFromContactID,
	FieldToContactID,
	FieldRelationType,
	FieldNotes,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// RelationType defines the type for the "relation_type" enum field.
type RelationType string

// RelationType values.
const (
	RelationTypeWife          RelationType = "wife"
	RelationTypeHusband       RelationType = "husband"
	RelationTypeMother        RelationType = "mother"
	RelationTypeFather        RelationType = "father"
	RelationTypeDaughter      RelationType = "daughter"
	RelationTypeSon           RelationType = "son"
	RelationTypeSister        RelationType = "sister"
	RelationTypeBrother       RelationType = "brother"
	RelationTypeGrandmother   RelationType = "grandmother"
	RelationTypeGrandfather   RelationType = "grandfather"
	RelationTypeGranddaughter RelationType = "granddaughter"
	RelationTypeGrandson      RelationType = "grandson"
	RelationTypeAunt          RelationType = "aunt"
	RelationTypeUncle         RelationType = "uncle"
	RelationTypeNiece         RelationType = "niece"
	RelationTypeNephew        RelationType = "nephew"
	RelationTypeCousin        RelationType = "cousin"
	RelationTypeFriend        RelationType = "friend"
	RelationTypeGodmother     RelationType = "godmother"
	RelationTypeGodfather     RelationType = "godfather"
	RelationTypeGoddaughter   RelationType = "goddaughter"
	RelationTypeGodson        RelationType = "godson"
	RelationTypeOther         RelationType = "other"
)

func (rt RelationType) String() string {
	return string(rt)
}

// RelationTypeValidator is a validator for the "relation_type" field enum values. It is called by the builders before save.
func RelationTypeValidator(rt RelationType) error {
	switch rt {
	case RelationTypeWife, RelationTypeHusband, RelationTypeMother, RelationTypeFather, RelationTypeDaughter, RelationTypeSon, RelationTypeSister, RelationTypeBrother, RelationTypeGrandmother, RelationTypeGrandfather, RelationTypeGranddaughter, RelationTypeGrandson, RelationTypeAunt, RelationTypeUncle, RelationTypeNiece, RelationTypeNephew, RelationTypeCousin, RelationTypeFriend, RelationTypeGodmother, RelationTypeGodfather, RelationTypeGoddaughter, RelationTypeGodson, RelationTypeOther:
		return nil
	default:
		return fmt.Errorf("relationship: invalid enum value for relation_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the Relationship queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFromContactID orders the results by the from_contact_id field.
func ByFromContactID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromContactID, opts...).ToFunc()
}

// ByToContactID orders the results by the to_contact_id field.
func ByToContactID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToContactID, opts...).ToFunc()
}

// ByRelationType orders the results by the relation_type field.
func ByRelationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationType, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByFromContactField orders the results by from_contact field.
func ByFromContactField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFromContactStep(), sql.OrderByField(field, opts...))
	}
}

// ByToContactField orders the results by to_contact field.
func ByToContactField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newToContactStep(), sql.OrderByField(field, opts...))
	}
}
func newFromContactStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FromContactInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FromContactTable, FromContactColumn),
	)
}
func newToContactStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ToContactInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ToContactTable, ToContactColumn),
	)
}
